const strings = {
  error: {
    server_error: "Server error, please try again",
    aiPromptTooLong: "AI prompt too long (max 4096 characters)",
  },
  title: {
    donate: "Donate",
    donateTitle: "Support P3X Redis UI",
    donateDescription: "P3X Redis UI is a free, open-source project. Maintaining the app, AI features, Docker images, servers, and infrastructure costs come out of the developer's own pocket. If you find this tool useful, please consider supporting its continued development with a donation. Every contribution helps keep the project alive and growing. Thank you!",
    jsonRecursive: "Expanding all leaves",
    name: "P3X Redis UI",
    nameDonated: "P3X Redis UI+",
    main: "You may choose a Redis connection to connect from the left bottom menu.",
    statistics: "Statistics",
    error: "Error",
    connectingRedis: "Connecting to Redis ...",
    socketioConnectError: "Socket.IO Error",
    db: "DB",
    server: "Server",
    clients: "Clients",
    memory: "Memory",
    persistence: "Persistence",
    stats: "Statistics",
    replication: "Replication",
    cpu: "CPU",
    cluster: "Cluster",
    modules: "Modules",
    errorstats: "Error Statistics",
    commandstats: "Command Statistics",
    latencystats: "Latency Statistics",
    keysizes: "Key Sizes",
    threads: "Threads",
  },
  confirm: {
    dropIndex: "Are you sure to drop this index?",
    uploadBuffer: "Are you sure to upload this binary data?",
    uploadBufferDone: "The binary data is uploaded",
    uploadBufferDoneAndSave: "The binary data is uploaded and saved on the server",
    title: "Confirm",
    alert: "Alert",
    info: "Info",
    deleteListItem: "Are you sure to delete this list item?",
    deleteHashKey: "Are you sure to delete this hash key item?",
    deleteStreamTimestamp: "Are you sure to delete this stream timestamp?",
    deleteSetMember: "Are you sure to delete this set member?",
    deleteZSetMember: "Are you sure to delete this sorted set member?",
    deleteConnection: "Confirm",
    deleteConnectionText: "Are you sure to delete this Redis connection?",
    deleteNode: "Are you sure to delete this Redis node?",
    deleteAllKeys: opts => {
      return `Delete this tree and all it\'s keys (${opts.key})?`;
    },
    deleteSearchKeys: opts => {
      return `Are you sure to delete all keys matching "${opts.pattern}"? Found ${opts.count} keys.`;
    },
    socketioConnectError: "Socket.IO cannot connect to the server, you can reload and try resolve the connection error yourself, the client does not know how to solve it itself.",
    socketioAuthRequired: "Socket.IO authorization is required. Please authenticate with HTTP Basic Auth (username/password) and reload.",
    invalidCredentials: "Invalid username or password.",
    delete: "Delete?",
    deleteKey: "Are you sure to delete this key?",
    rename: {
      title: "Are you sure to rename this key?",
      textContent: "This action renames the key permanently.",
      placeholder: "The Redis key (required)"
    },
    ttl: {
      title: "Are you sure you want to change this key's TTL?",
      textContent: "Changing the TTL updates this key's time to live. Leave empty to keep this key forever.",
      placeholder: "The Redis key's TTL (integer or empty)",
      placeholderPlaceholder: "Empty means it persists forever; otherwise enter an integer.",
      convertTextToTime: "Convert text to time",
      convertTextToTimePlaceholder: "Eg. 1d will be 86400"
    },
  },
  language: {
    // When you translate the english name, keep the Language in English
    // eg. Inglés / English
    bg: "Български / Bulgarian",
    cs: "Čeština / Czech",
    de: "Deutsch / German",
    el: "Ελληνικά / Greek",
    en: "English",
    es: "Español / Spanish",
    fr: "Français / French",
    hu: "Magyar / Hungarian",
    it: "Italiano / Italian",
    ja: "日本語 / Japanese",
    nl: "Nederlands / Dutch",
    pl: "Polski / Polish",
    "pt-PT": "Português / Portuguese",
    ro: "Română / Romanian",
    ru: "Русский / Russian",
    sk: "Slovenčina / Slovak",
    sr: "Српски / Serbian",
    sv: "Svenska / Swedish",
    tr: "Türkçe / Turkish",
    uk: "Українська / Ukrainian",
    zn: "中文 / Chinese",
    ar: "العربية / Arabic",
    az: "Azərbaycanca / Azerbaijani",
    be: "Беларуская / Belarusian",
    bn: "বাংলা / Bengali",
    da: "Dansk / Danish",
    et: "Eesti / Estonian",
    fi: "Suomi / Finnish",
    fil: "Filipino / Filipino",
    he: "עברית / Hebrew",
    hr: "Hrvatski / Croatian",
    hy: "Հայերեն / Armenian",
    id: "Bahasa Indonesia / Indonesian",
    ka: "ქართული / Georgian",
    kk: "Қазақша / Kazakh",
    km: "ខ្មែរ / Khmer",
    ko: "한국어 / Korean",
    ky: "Кыргызча / Kyrgyz",
    lt: "Lietuvių / Lithuanian",
    mk: "Македонски / Macedonian",
    ms: "Bahasa Melayu / Malay",
    ne: "नेपाली / Nepali",
    no: "Norsk / Norwegian",
    "pt-BR": "Português (Brasil) / Portuguese (Brazil)",
    sl: "Slovenščina / Slovenian",
    tg: "Тоҷикӣ / Tajik",
    th: "ไทย / Thai",
    vi: "Tiếng Việt / Vietnamese",
    "zh-HK": "中文（香港） / Chinese (Hong Kong)",
    "zh-TW": "中文（台灣） / Chinese (Taiwan)",
    bs: 'Bosanski / Bosnian',
    si: 'සිංහල / Sinhala',
    sw: 'Kiswahili / Swahili',
    ta: 'தமிழ் / Tamil'
  },
  intention: {
    copy: "Copy",
    downloadBuffer: "Download binary",
    setBuffer: "Upload binary",
    exportKeys: "Export keys",
    exportAllKeys: (opts) => `Export all ${opts.count} keys`,
    exportSearchResults: (opts) => `Export ${opts.count} results`,
    importKeys: "Import keys",
    deleteSearchKeys: (opts) => `Delete ${opts.count} matching keys`,
    deleteAllKeysMenu: (opts) => `Delete all ${opts.count} keys`,
    saveWithFormatJson: "Save with format",
    formatJson: "Format Json",
    wrap: "Wrap",
    unwrap: "Unwrap",
    downloadJson: "Download JSON",
    pubsubMonitor: "PubSub",
    pulse: "Pulse",
    profiler: "Profiler",
    memoryAnalysis: "Analysis",
    // When you translate the language, keep the Language in English
    // eg. Idioma / Language
    language: "Language",
    ok: "OK",
    addKey: "Add to this key",
    addKeyRoot: "Add a root key",
    reloadKey: "Reload key",
    reload: "Reload",
    close: "Close",
    commands: "Commands",
    view: "View",
    statistics: "Statistics",
    refresh: "Refresh",
    pause: "Pause",
    resume: "Resume",
    clear: "Clear",
    rename: "Rename",
    main: "Database",
    cancel: "Cancel",
    theme: "Theme",
    github: "GitHub",
    githubRepo: "Repository",
    githubRelease: "Releases",
    githubChangelog: "Changelog",
    info: "Info",
    settings: "Settings",
    connect: "Connect",
    disconnect: "Disconnect",
    logout: "Logout",
    overview: "Overview",
    console: "Console",
    noConnections: "No connections, add a connection in the settings menu.",
    noConnectionsInSettings: "No connections, you may add a NEW CONNECTION above.",
    connectionAdd: "New connection",
    addGroup: "Add Group",
    extend: "Extend",
    collapse: "Collapse",
    add: "Add",
    edit: "Edit",
    save: "Save",
    ttl: "Set TTL",
    fieldTtl: "Field TTL",
    digest: "Digest",
    delete: "Delete",
    remove: "Remove",
    sure: "Sure",
    areYouSure: "Are you sure?",
    testConnection: "Test connection",
    getKey: "Loading Redis key and associated data ...",
    jsonViewShow: "Display JSON",
    jsonViewEditor: "Edit JSON",
    quickConsole: "Quick Console",
    moveUp: "Move up",
    moveDown: "Move down",
  },
  diff: {
    reviewChanges: "Review changes",
    inline: "Inline",
    sideBySide: "Side by side",
    additions: "additions",
    deletions: "deletions",
    unchangedLines: "unchanged lines",
    noChanges: "No changes detected",
    before: "Before",
    after: "After",
  },
  label: {
    id: {
      nodeId: 'Node ID',
      id: "Connection ID",
      info: "If you do not wan't to change the properties of: sshPassword, sshPrivateKey, password, tlsCrt, tlsKey, tlsCa, please enter the ID of the connection in those propertes to keep the property values intact. If you want the same logic in the node password, then enter the node ID in the node password."
    },
    secureFeature: 'If you see a value that starts with a P3X an look like the same, it is a secure feature. To change the settings, just replace these settings with empty or something else and they will be saved. If you do not change the settings, the settings will be kept as they are on the server.',
    aiTranslating: "Translating...",
    aiSettings: "AI Settings",
    desktopNotifications: "Desktop Notifications",
    desktopNotificationsEnabled: "Enable desktop notifications",
    desktopNotificationsInfo: "Receive OS notifications for Redis disconnections and reconnections when the app is not focused.",
    aiGroqApiKey: "Groq API Key",
    aiGroqApiKeyInfo: "Optional. Your own Groq API key for better performance. Get a free key from",
    aiGroqApiKeyPlaceholder: "gsk_...",
    aiGroqApiKeySaved: "AI settings saved",
    aiGroqApiKeyInvalid: "Invalid Groq API key",
    aiGroqApiKeyNotSet: "Not set (using server default)",
    aiEnabled: "AI Enabled",
    aiEnabledYes: "Yes",
    aiEnabledNo: "No",
    aiRouteViaNetwork: "Route via network.corifeus.com",
    aiRoutingDirect: "Queries go directly to Groq using your own API key, bypassing network.corifeus.com.",
    aiRoutingNetwork: "AI queries are routed through network.corifeus.com. If you have your own free Groq API key, you can turn off this switch to route directly to Groq without network.corifeus.com.",
    aiMaxTokens: "AI Max Tokens",
    aiMaxTokensInfo: "Maximum number of tokens for AI responses. Higher values allow longer responses but may use more API credits.",
    ssh: {
      on: 'SSH on',
      off: 'SSH off',
      sshHost: 'SSH Host',
      sshPort: 'SSH port',
      sshUsername: 'SSH username',
      sshPassword: 'SSH password',
      sshPrivateKey: 'SSH private key'
    },
    isBuffer: opts => `[object ArrayBuffer] means that the value is binary data or the value is bigger than ${opts.maxValueAsBuffer}`,
    streamValue: `Stream field and value is a oneliner. Eg.: field1 value1 "field 2" "value 2"`,
    streamTimestampId: `'*' means auto generated or the specification as <millisecondsTime>-<sequenceNumber>`,
    unableToLoadKey: ({
      key
    }) => {
      return `Unable to load this key: ${key}. Possible, the key was deleted. The exact error is in the console.`;
    },
    bigJson: "This JSON object is over 10 kb, so make sure you know what you doing, because some functions can be slow rendering.",
    addNode: "Add node",
    validateJson: "Validate JSON",
    reducedFunction: `Reduced functionality`,
    tooManyKeys: opts => {
      return `For the full maximum functions allowed keys total is ${opts.maxLightKeysCount} count. This database has over the allowed keys in total ${opts.count}. The key sorting and the additional fancy tree information is disabled. The searching is happening only on the server instead the client search.`;
    },
    redisCommandNotFound: "No Redis command match found ...",
    treeKeyStore: `The sorting (natural compare) is executed on the client aka the browser, which means it has a penalty for big large sets, like over 10k keys, it might add a little time to the page rendering. There is no key sorting in Redis, only like this.`,
    socketIoTimeout: options => {
      return `The Socket.IO timed out for this request (max ${options.timeout / 1000} seconds) ...`;
    },
    resizerInfo: options => {
      return `Left or right panel minimum width is ${options.width}px`;
    },
    jsonViewNotParsable: "This value is not JSON parsable  ",
    ttlTitle: "Set the TTL in seconds",
    passwordSecure: "The password might will be empty, but still it will show characters, this is a security feature.",
    tlsWithoutCert: "Enable TLS without additional certificate",
    tlsRejectUnauthorized: "Reject unauthorized certificate",
    tlsSecure: "If you see a TLS configuration that starts with a P3X or all the TLS settings look like the same, it is a secure feature. To change the settings, just replace these settings with empty or something else and they will be saved. If you do not change the TLS settings, the settings will be kept as they are on the server.",
    treeSeparatorEmpty: "If the tree separator is empty, the tree wil have no nested nodes, just a pure list",
    treeSeparatorEmptyNote: "No nested nodes, just a pure list",
    welcomeConsole: "Welcome to the Redis Console",
    welcomeConsoleInfo: "Cursor UP or DOWN history is enabled",
    redisListIndexInfo: "Empty to append, -1 to prepend or save it to the position shown.",
    console: "Console",
    connectiondAdd: "Add connection",
    connectiondEdit: "Edit connection",
    connectiondView: "View connection",
    connections: "Connections",
    keysSort: {
      on: "Key sorting on",
      off: "Key sorting off"
    },
    cluster: {
      on: "Cluster on",
      off: "Cluster off"
    },
    sentinel: {
      on: "Sentinel on",
      off: "Sentinel off",
      name: "Sentinel name"
    },
    readonly: {
      on: "Readonly on",
      off: "Readonly off"
    },
    theme: {
      light: "Light",
      dark: "Dark enterprise",
      darkNeu: "Dark",
      darkoBluo: "Darko bluo",
      enterprise: "Enterprise",
      redis: "Redis",
      matrix: "Matrix"
    },
    connected: opts => {
      return `Connected: ${opts.name}`;
    },
    tree: "Tree",
    askAuth: "Ask for authorization",
    keyboardShortcuts: "Keyboard Shortcuts",
    about: "About",
    supportedLanguages: "Supported Languages",
    version: "Version",
    redisVersion: "Redis Version",
    modules: "Modules",
    shortcutRefresh: "Refresh",
    shortcutSearch: "Focus Search",
    shortcutNewKey: "New Key",
    shortcutDisconnect: "Disconnect",
    themeAuto: "Auto (system)",
    languageAuto: "Auto (system)",
    shortcutCommandPalette: "Command Palette",
    commandPalette: "Command Palette",
    noResults: "No results",
    redisCommandsReference: "Redis Commands",
    connectFirst: "Connect to a Redis server first",
    ungrouped: "Ungrouped",
    grouped: "Grouped",
    searchLanguage: "Search language...",
    exportProgress: "Exporting keys...",
    importProgress: "Importing keys...",
    importPreview: "Preview",
    importOverwrite: "Overwrite",
    importSkip: "Skip",
    importConflict: "If key already exists:",
    noKeysToExport: "No keys to export",
    type: "Type",
    time: "Time",
    format: "Format",
    loading: "Loading...",
    autoRefresh: "Auto",
    importNoKeys: "No keys found in file",
    exportSearchHint: "Exporting only keys matching current search",
    importSearchHint: "Import applies to the full database, not just search results",
    deleteSearchHint: "Deletes all keys matching the current search on the server",
    deletingSearchKeys: "Deleting matching keys...",
  },
  status: {
    dataCopied: "The data is in the clipboard",
    exportDone: "Export complete",
    deletedSearchKeys: (opts) => `Deleted ${opts.count} keys`,
    indexCreated: "Index created",
    indexDropped: "Index dropped",
    importDone: (opts) => `Import complete: ${opts.created} created, ${opts.skipped} skipped, ${opts.errors} errors`,
    nodeRemoved: "Node removed",
    keyIsNotExisting: "This key could have been deleted or expired.",
    keyCount: opts => {
      if (opts.keyCount === 0) {
        return "No key";
      } else if (opts.keyCount === 1) {
        return "1 key";
      } else {
        return `${opts.keyCount} keys`;
      }
    },
    treeExpandAll: "Expand all tree leaves. This operation can be expensive and may take time ...",
    noRedisKeys: "There are no keys in this database.",
    redisConnected: "Redis connected successful",
    reverted: "Reverted",
    connectionRestored: "Connection restored",
    reloadingDataInfo: "Reloading Redis data info",
    added: "Added",
    saved: "Updated",
    cancelled: "Cancelled",
    deleted: "Deleted",
    savedRedis: "Redis data is saved",
    redisDisconnected: opts => {
      return `The current connection had an error: ${opts.error.message}`;
    },
    dbChanged: opts => {
      return `The db index set to ${opts.db}. `;
    },
    treeDeleted: opts => {
      return `The tree key was deleted (${opts.key}).`;
    },
    deletedKey: opts => {
      return `The key was deleted (${opts.key}).`;
    },
    renamedKey: "This key has been renamed",
    ttlChanged: "This key's TTL has been changed",
    notInteger: "This input is not an integer",
    persisted: "This key is persisted forever",
    set: "The key is set/added"
  },
  code: {
    "delete-connection": "This connection was deleted, so you are disconnected to this Redis instance.",
    "save-connection": "This connection was changed, so you are disconnected to this Redis instance. You may re-connect.",
    "readonly-connections": "Connections add/save/delete are readonly only!",
    "readonly-connection-mode": "This connection is read only mode!",
    "list-out-of-bounds": "This list index is out of bounds",
    "invalid-json-value": "The value is not valid JSON.",
    "http_auth_required": "Authorization required: please authenticate with HTTP Basic Auth and reload.",
    "auto-connection-failed": "Possible, the connection was removed and the auto connection failed, because of this.",
    invalid_console_command: "This command is not working via the GUI.",
    AI_DISABLED: "AI is disabled. Enable it in AI Settings.",
    AI_PROMPT_REQUIRED: "AI prompt is required.",
    GROQ_API_KEY_READONLY: "The Groq API key is read-only and cannot be modified.",
    blocked_api_access: "Your Groq API plan does not allow access to this model. Please upgrade your Groq plan or use the network.corifeus.com proxy.",
    rate_limit: "AI rate limit reached. Try again later or use your own Groq API key in Settings.",
  },
  form: {
    error: {
      required: "Required",
      port: "The port is between 1-65535",
      invalid: "The form is invalid"
    },
    connection: {
      label: {
        name: "Name",
        group: "Group",
        host: "Hostname",
        port: "Port",
        password: "Password",
        username: "Username"
      }
    },
    treeSettings: {
      maxValueDisplay: "Max value display string length",
      maxValueDisplayInfo: "If set to 0, show full values. If greater than 0, truncate to this length. If -1: for strings, hide the value until edit; for other types, show full content.",
      maxKeys: "The max key count",
      maxKeysInfo: "So that the GUI does not crash, we limit the max key count.",
      keyCount: (opts) => {
        return `Number of keys: ${opts?.keyCount ?? 0}`;
      },
      label: {
        animation: "Use animation",
        noAnimation: "No animation",
        undoEnabled: "Undo enabled",
        undoDisabled: "Undo disabled",
        diffEnabled: "Show diff before saving",
        diffDisabled: "Diff before save disabled",
        jsonFormatTwoSpace: "Format JSON with 2 spaces",
        jsonFormatFourSpace: "Format JSON with 4 spaces",
        formName: "Redis settings",
        searchModeClient: "Client search mode",
        searchModeServer: "Server search mode",
        searchModeStartsWith: "Search with starts with mode",
        searchModeIncludes: "Search includes mode"
      },
      undoHint: "Undo is available for string and JSON key types only",
      field: {
        treeSeparator: "Tree separator",
        treeSeparatorSelector: "Tree separator selector",
        page: "Tree paging count",
        keyPageCount: "Key paging count",
        keysSort: "Sort the keys",
        searchMode: "Search mode",
        searchModeStartsWith: "Search starts with / includes"
      },
      error: {
        keyPageCount: "The key page count must be an integer between 5 - 100",
        page: "The page count must be an integer between 10 - 5000",
        maxValueDisplay: "The maximum display value must be an integer between -1 and 32768",
        maxKeys: "The maximum key count value must be an integer between 100 and 100000"
      }
    },
    key: {
      label: {
        formName: {
          add: "Add new Redis key",
          edit: "Edit Redis key",
          append: "Add to existing Redis key"
        }
      },
      field: {
        streamTimestamp: "Timestamp",
        key: "Key",
        type: "Type",
        index: "Index",
        hashKey: "Hash key",
        score: "Score",
        value: "Value",
        errorRate: "Error rate",
        capacity: "Capacity",
        topk: "Top K",
        width: "Width",
        depth: "Depth",
        decay: "Decay",
        compression: "Compression",
        increment: "Increment",
        item: "Item",
        vectorValues: "Vector values (comma-separated)",
        element: "Element name",
      },
      error: {
        streamTimestamp: "The timestamp is required, either Redis format or as *",
        key: "The key is, at least, one character",
        hashKey: "The hash table key is at least one character",
        score: "The sorted set score is required",
        value: "The value is required",
        errorRate: "Error rate must be between 0 and 1 (e.g. 0.01)",
        capacity: "Capacity must be a positive integer",
        topk: "Top K must be a positive integer",
        width: "Width must be a positive integer",
        depth: "Depth must be a positive integer",
        item: "The item is required",
      }
    },
    main: {
      label: {
        database: "DB"
      }
    }
  },
  page: {
    search: {
      title: "Search",
      index: "Index",
      query: "Query",
      results: "Results",
      noIndex: "No indexes found",
      createIndex: "Create Index",
      dropIndex: "Drop Index",
      indexInfo: "Index Info",
      indexName: "Index Name",
      prefix: "Key Prefix (optional)",
      fieldName: "Field Name",
      hybridMode: "Hybrid Search (FT.HYBRID)",
      vectorField: "Vector Field",
      vectorValues: "Vector Values",
    },
    monitor: {
      title: "Monitoring",
      memory: "Memory",
      opsPerSec: "Ops/sec",
      clients: "Clients",
      blocked: "Blocked",
      hitsMisses: "Hit Rate",
      networkIo: "Network I/O",
      slowLog: "Slow Log",
      totalCommands: "Total",
      expired: "Expired",
      evicted: "Evicted",
      clientList: "Client List",
      topKeys: "Top Keys by Memory",
      killClient: "Kill client",
      clientKilled: "Client killed",
      confirmKillClient: "Are you sure to kill this client?",
      noKeys: "No keys",
      rss: "RSS",
      peak: "Peak",
      fragmentation: "Fragmentation",
      hitsAndMisses: "Hits / Misses",
      noClients: "No clients",
      slotStats: "Cluster Slot Stats",
      serverInfo: "Server Info",
      os: "OS",
      port: "Port",
      pid: "Process ID",
      configFile: "Config File",
      uptime: "Uptime",
      keyspace: "Keyspace",
      keys: "Keys",
      expires: "Expires",
      noKeyspace: "No keys",
      persistence: "Persistence",
      rdbLastSave: "RDB Last Save",
      rdbStatus: "RDB Status",
      rdbChanges: "Changes Since Last Save",
      aofEnabled: "AOF Enabled",
      aofSize: "AOF Size",
      replication: "Replication",
      role: "Role",
      replicas: "Connected Replicas",
      masterHost: "Master Host",
      linkStatus: "Link Status",
      cpu: "CPU Usage",
      cpuSys: "System",
      cpuUser: "User",
      modules: "Loaded Modules",
      noModules: "No modules loaded",
    },
    analysis: {
      title: "Memory Analysis",
      runAnalysis: "Run Analysis",
      running: "Analyzing...",
      typeDistribution: "Type Distribution",
      prefixMemory: "Memory by Prefix",
      topKeysByMemory: "Top Keys by Memory",
      expirationOverview: "Key Expiration",
      memoryBreakdown: "Memory Breakdown",
      keysScanned: "Keys Scanned",
      totalMemory: "Total Memory",
      rssMemory: "RSS Memory",
      peakMemory: "Peak Memory",
      luaMemory: "Lua Memory",
      overheadMemory: "Overhead",
      datasetMemory: "Dataset",
      fragmentation: "Fragmentation",
      allocator: "Allocator",
      withTTL: "With TTL",
      persistent: "Persistent",
      avgTTL: "Average TTL",
      prefix: "Prefix",
      keyCount: "Key Count",
      memoryUsage: "Memory Usage",
      noPrefix: "(no prefix)",
      topN: "Top N",
      maxScanKeys: "Max Scan Keys",
      type: "Type",
      noData: "No data. Click Run Analysis to start.",
      exportAll: "Export All",
    },
    overview: {
      noConnected: "There is no connection to Redis.",
      overviewClients: "List the connected by the count of clients",
      connectedCount: opt => {
        if (opt.length === 1) {
          return "1 client";
        }
        return `${opt.length} clients`;
      }
    },
    key: {
      label: {
        key: "Key",
        encoding: "Encoding",
        compression: "Compression",
        aiRateLimited: "AI rate limit reached. Try again later or use your own Groq API key in Settings.",
        aiError: "AI query failed",
        length: "Size",
        ttl: "TTL",
        ttlTitle: "Time To Live",
        type: "Type",
        ttlNotExpire: "does not expire",
        lengthString: "bytes",
        lengthItem: "items",
        actions: "Actions"
      },
      list: {
        table: {
          index: "Index",
          value: "Value"
        }
      },
      hash: {
        table: {
          hashkey: "Hashkey",
          value: "Value"
        }
      },
      set: {
        table: {
          value: "Member"
        }
      },
      zset: {
        table: {
          value: "Member",
          score: "Score"
        }
      },
      stream: {
        table: {
          timestamp: "Timestamp ID",
          field: "Field",
          value: "Value"
        }
      },
      timeseries: {
        chart: "Chart",
        info: "Info",
        addPoint: "Add Data Point",
        from: "From (ms or -)",
        to: "To (ms or +)",
        aggregation: "Aggregation",
        timeBucket: "Bucket (ms)",
        none: "None",
        dataPoints: "data points",
        labels: "Labels",
        rules: "Rules",
        retention: "Retention",
        timestamp: "Timestamp",
        value: "Value",
        retentionHint: "0 = no expiry, or milliseconds",
        duplicatePolicy: "Duplicate policy",
        labelsHint: "key1 value1 key2 value2",
        timestampHint: "'*' means auto generated, or milliseconds timestamp",
        editAllHint: "One data point per line: timestamp value (timestamp can be * for auto)",
        autoSpread: "Auto * spread interval",
        formula: "Formula",
        formulaLinear: "Linear",
        formulaRandom: "Random",
        formulaSawtooth: "Sawtooth",
        formulaPoints: "Points",
        formulaAmplitude: "Amplitude",
        formulaOffset: "Offset",
        generate: "Generate",
        overlay: "Overlay keys",
        overlayHint: "Comma-separated keys",
        exportChart: "Export PNG",
        mrangeFilter: "Label filter",
        mrangeHint: "e.g. sensor=temp",
        bulkMode: "Bulk generate"
      },
      probabilistic: {
        info: "Info",
        addItem: "Add Item",
        checkItem: "Check Item",
        item: "Item",
        exists: "Exists",
        doesNotExist: "Does not exist",
        topkList: "Top Items",
        topkCount: "Count",
        queryCount: "Query Count",
        queryResult: "Query Result",
        addedSuccessfully: "Item added successfully",
        deletedSuccessfully: "Item deleted successfully",
        quantile: "Quantile",
        quantileResult: "Result",
        noItems: "No items to display",
        resetConfirm: "Reset all data in this T-Digest?",
      },
      vectorset: {
        info: "Info",
        elements: "Elements",
        similarity: "Similarity Search",
        searchByElement: "Search by element",
        searchByVector: "Search by vector",
        vectorValues: "Vector values",
        element: "Element",
        score: "Score",
        count: "Count",
        addElement: "Add Element",
        attributes: "Attributes",
        noAttributes: "No attributes",
        dimensions: "Dimensions",
        removeConfirm: "Remove this element from the VectorSet?",
        noElements: "No elements",
        filter: "Filter",
        searchComplete: "Search complete",
      }
    },
    treeControls: {
      settings: "Tree settings",
      expandAll: "Expand all",
      collapseAll: "Collapse all",
      level: "Level",
      search: {
        search: "Search in the keys",
        clear: "Clear current search to set empty",
        placeholderClient: "Search client side",
        placeholderServer: "Search server side",
        info: (opts) => "The client side search means, that it matches the text in the search input. The server side search means, that is it like search in the keys patterns as *{search-text}*. For large search sets, it is better to use server side searching. For smaller search sets, it is better to use client side search mode." + ` If the keys count is over ${opts?.maxLightKeysCount ?? 110000}, you can only search on server side.`,
        largeSetInfo: "In a large set, client side searching is disabled. so right now only server side searching is possible.",
        infoDetails: "To find out how the search works, please check out the settings"
      },
      pager: {
        next: "Next",
        prev: "Previous",
        first: "First",
        last: "Last"
      }
    }
  },
  time: {
    years: "years",
    months: "months",
    days: "days",
    year: "year",
    month: "month",
    day: "day",
    second: "second",
    seconds: "seconds",
    minute: "minute",
    minutes: "minutes",
    hour: "hour",
    hours: "hours"
  },
  redisTypes: {
    string: "String",
    list: "List",
    hash: "Hash table",
    set: "Set",
    zset: "Sorted set - zset",
    stream: "Stream",
    json: "JSON",
    timeseries: "Time Series",
    bloom: "Bloom filter",
    cuckoo: "Cuckoo filter",
    topk: "Top-K",
    cms: "Count-Min Sketch",
    tdigest: "T-Digest",
    vectorset: "VectorSet",
  }
};
module.exports = strings;
