const strings = {
  error: {
    server_error: "Serverfeil, prøv igjen",
    aiPromptTooLong: "AI-prompten er for lang (maks 4096 tegn)",
  },
  title: {
    donate: "Doner",
    donateTitle: "Støtt P3X Redis UI",
    donateDescription: "P3X Redis UI er et gratis åpen kildekode-prosjekt. Kostnadene for vedlikehold av appen, AI-funksjoner, Docker-bilder, servere og infrastruktur kommer fra utviklerens egen lomme. Hvis du synes dette verktøyet er nyttig, vurder å støtte den videre utviklingen med en donasjon. Ethvert bidrag hjelper prosjektet å leve og vokse. Takk!",
    jsonRecursive: "Utvider alle blader",
    name: "P3X Redis UI",
    nameDonated: "P3X Redis UI+",
    main: "Du kan velge en Redis-tilkobling for å koble til fra menyen nederst til venstre.",
    statistics: "Statistikk",
    error: "Feil",
    connectingRedis: "Kobler til Redis ...",
    socketioConnectError: "Socket.IO Feil",
    db: "DB",
    server: "Server",
    clients: "Kunder",
    memory: "Minne",
    persistence: "Utholdenhet",
    stats: "Statistikk",
    replication: "Replikering",
    cpu: "CPU",
    cluster: "Cluster",
    modules: "Moduler",
    errorstats: "Feilstatistikk",
    commandstats: "Kommandostatistikk",
    latencystats: "Latensstatistikk",
    keysizes: "Nøkkelstørrelser",
    threads: "Tråder"
  },
  confirm: {
    dropIndex: "Er du sikker på at du vil slette denne indeksen?",
    uploadBuffer: "Er du sikker på at du laster opp disse binære dataene?",
    uploadBufferDone: "De binære dataene lastes opp",
    uploadBufferDoneAndSave: "De binære dataene lastes opp og lagres på serveren",
    title: "Bekreft",
    alert: "Varsel",
    info: "Info",
    deleteListItem: "Er du sikker på at du vil slette dette listeelementet?",
    deleteHashKey: "Er du sikker på at du vil slette dette hash-nøkkelelementet?",
    deleteStreamTimestamp: "Er du sikker på at du vil slette dette tidsstempelet for strømmen?",
    deleteSetMember: "Er du sikker på at du vil slette dette settemedlemmet?",
    deleteZSetMember: "Er du sikker på at du vil slette dette sorterte settmedlemmet?",
    deleteConnection: "Bekreft",
    deleteConnectionText: "Er du sikker på å slette denne Redis-tilkoblingen?",
    deleteNode: "Er du sikker på å slette denne Redis-noden?",
    deleteAllKeys: opts => {
      return `Slett dette treet og alle dets nøkler (${opts.key})?`;
    },
    deleteSearchKeys: opts => {
      return `Er du sikker på at du vil slette alle nøkler som matcher "${opts.pattern}"? Fant ${opts.count} nøkler.`;
    },
    socketioConnectError: "Socket.IO kan ikke koble til serveren, du kan laste inn på nytt og prøve å løse tilkoblingsfeilen selv, klienten vet ikke hvordan den skal løse det selv.",
    socketioAuthRequired: "Socket.IO-autorisasjon kreves. Vennligst autentiser med HTTP Basic Auth (brukernavn/passord) og last inn på nytt.",
    invalidCredentials: "Ugyldig brukernavn eller passord.",
    delete: "Slette?",
    deleteKey: "Er du sikker på at du vil slette denne nøkkelen?",
    rename: {
      title: "Er du sikker på at du vil gi nytt navn til denne nøkkelen?",
      textContent: "Denne handlingen gir nytt navn til nøkkelen permanent.",
      placeholder: "Redis-nøkkelen (påkrevd)"
    },
    ttl: {
      title: "Er du sikker på at du vil endre denne nøkkelens TTL?",
      textContent: "Å endre TTL oppdaterer denne nøkkelens tid til å leve. La den stå tom for å beholde denne nøkkelen for alltid.",
      placeholder: "Redis-nøkkelens TTL (heltall eller tom)",
      placeholderPlaceholder: "Tom betyr at den vedvarer for alltid; ellers skriv inn et heltall.",
      convertTextToTime: "Konverter tekst til tid",
      convertTextToTimePlaceholder: "F.eks. 1d vil være 86400"
    }
  },
  language: {
    ar: "العربية / Arabic",
    az: "Azərbaycanca / Azerbaijani",
    be: "Беларуская / Belarusian",
    bg: "Български / Bulgarian",
    bn: "বাংলা / Bengali",
    cs: "Čeština / Czech",
    da: "Dansk / Danish",
    de: "Deutsch / German",
    el: "Ελληνικά / Greek",
    en: "English",
    es: "Español / Spanish",
    et: "Eesti / Estonian",
    fi: "Suomi / Finnish",
    fil: "Filipino / Filipino",
    fr: "Français / French",
    he: "עברית / Hebrew",
    hr: "Hrvatski / Croatian",
    hu: "Magyar / Hungarian",
    hy: "Հայերեն / Armenian",
    id: "Bahasa Indonesia / Indonesian",
    it: "Italiano / Italian",
    ja: "日本語 / Japanese",
    ka: "ქართული / Georgian",
    kk: "Қазақша / Kazakh",
    km: "ខ្មែរ / Khmer",
    ko: "한국어 / Korean",
    ky: "Кыргызча / Kyrgyz",
    lt: "Lietuvių / Lithuanian",
    mk: "Македонски / Macedonian",
    ms: "Bahasa Melayu / Malay",
    ne: "नेपाली / Nepali",
    nl: "Nederlands / Dutch",
    no: "Norsk / Norwegian",
    pl: "Polski / Polish",
    "pt-BR": "Português (Brasil) / Portuguese (Brazil)",
    "pt-PT": "Português / Portuguese",
    ro: "Română / Romanian",
    ru: "Русский / Russian",
    sk: "Slovenčina / Slovak",
    sl: "Slovenščina / Slovenian",
    sr: "Српски / Serbian",
    sv: "Svenska / Swedish",
    tg: "Тоҷикӣ / Tajik",
    th: "ไทย / Thai",
    tr: "Türkçe / Turkish",
    uk: "Українська / Ukrainian",
    vi: "Tiếng Việt / Vietnamese",
    "zh-HK": "中文（香港） / Chinese (Hong Kong)",
    "zh-TW": "中文（台灣） / Chinese (Taiwan)",
    zn: "中文 / Chinese",
    bs: 'Bosanski / Bosnian',
    si: 'සිංහල / Sinhala',
    sw: 'Kiswahili / Swahili',
    ta: 'தமிழ் / Tamil'
  },
  intention: {
    copy: "Kopier",
    downloadBuffer: "Last ned binær",
    setBuffer: "Last opp binær",
    exportKeys: "Eksporter nøkler",
    exportAllKeys: (opts) => `Eksporter alle ${opts.count} nøkler`,
    exportSearchResults: (opts) => `Eksporter ${opts.count} resultater`,
    deleteAllKeysMenu: (opts) => `Slett alle ${opts.count}`,
    importKeys: "Importer nøkler",
    deleteSearchKeys: (opts) => `Slett ${opts.count} matchende nøkler`,
    saveWithFormatJson: "Lagre med format",
    formatJson: "Format Json",
    wrap: "Pakk inn",
    unwrap: "Pakk ut",
    downloadJson: "Last ned JSON",
    pubsubMonitor: "PubSub",
    pulse: "Pulse",
    profiler: "Profiler",
    memoryAnalysis: "Analysis",
    // When you translate the language, keep the Language in English
    // eg. Idioma / Language
    language: "Språk",
    ok: "OK",
    addKey: "Legg til denne nøkkelen",
    addKeyRoot: "Legg til en rotnøkkel",
    reloadKey: "Last inn nøkkelen på nytt",
    reload: "Last inn på nytt",
    close: "Lukk",
    commands: "Kommandoer",
    view: "Visning",
    statistics: "Statistikk",
    refresh: "Oppdater",
    pause: "Pause",
    resume: "Gjenoppta",
    clear: "Klart",
    rename: "Gi nytt navn",
    main: "Database",
    cancel: "Avbryt",
    theme: "Tema",
    github: "GitHub",
    githubRepo: "Depot",
    githubRelease: "Utgivelser",
    githubChangelog: "Endringslogg",
    info: "Info",
    settings: "Innstillinger",
    connect: "Koble til",
    disconnect: "Koble fra",
    logout: "Logg ut",
    overview: "Oversikt",
    console: "Konsoll",
    noConnections: "Ingen tilkoblinger, legg til en tilkobling i innstillingsmenyen.",
    noConnectionsInSettings: "Ingen tilkoblinger, du kan legge til en NY TILKOBLING ovenfor.",
    connectionAdd: "Ny tilkobling",
    addGroup: "Legg til gruppe",
    extend: "Forleng",
    collapse: "Skjul sammen",
    add: "Legg til",
    edit: "Rediger",
    save: "Lagre",
    ttl: "Sett TTL",
    fieldTtl: "Felt TTL",
    digest: "Sammendrag",
    delete: "Slett",
    remove: "Fjern",
    areYouSure: "Er du sikker?",
    sure: "Klart det",
    testConnection: "Test tilkobling",
    getKey: "Laster inn Redis-nøkkel og tilhørende data ...",
    jsonViewShow: "Vis JSON",
    jsonViewEditor: "Rediger JSON",
    quickConsole: "Hurtigkonsoll",
    moveUp: "Flytt opp",
    moveDown: "Flytt ned",
  },
  diff: {
    reviewChanges: "Gjennomg\u00e5 endringer",
    inline: "Innebygd",
    sideBySide: "Side ved side",
    additions: "tilf\u00f8yelser",
    deletions: "slettinger",
    unchangedLines: "uendrede linjer",
    noChanges: "Ingen endringer oppdaget",
    before: "F\u00f8r",
    after: "Etter",
  },
  label: {
    id: {
      nodeId: "Node ID",
      id: "Tilkoblings-ID",
      info: "Hvis du ikke vil endre egenskapene til: sshPassword, sshPrivateKey, passord, tlsCrt, tlsKey, tlsCa, vennligst skriv inn ID-en til tilkoblingen i disse egenskapene for å holde egenskapsverdiene intakte. Hvis du vil ha samme logikk i nodepassordet, skriv inn node-ID i nodepassordet."
    },
    secureFeature: "Hvis du ser en verdi som starter med en P3X og ser ut som den samme, er det en sikker funksjon. For å endre innstillingene, erstatt disse innstillingene med tomme eller noe annet, og de vil bli lagret. Hvis du ikke endrer innstillingene, beholdes innstillingene slik de er på serveren.",
    aiTranslating: "Oversetter...",
    aiSettings: "AI-innstillinger",
    aiGroqApiKey: "Groq API-nøkkel",
    aiGroqApiKeyInfo: "Valgfritt. Egen Groq API-nøkkel for bedre ytelse. Skaff en gratis nøkkel på",
    aiGroqApiKeyPlaceholder: "gsk_...",
    aiGroqApiKeySaved: "AI API-nøkkel lagret",
    aiGroqApiKeyInvalid: "Ugyldig Groq API-nøkkel",
    aiGroqApiKeyNotSet: "Ikke satt (serverstandard)",
    aiEnabled: "AI aktivert",
    aiEnabledYes: "Ja",
    aiEnabledNo: "Nei",
    aiRouteViaNetwork: "Rute via network.corifeus.com",
    aiRoutingDirect: "Spørringer går direkte til Groq med din egen API-nøkkel, uten å gå via network.corifeus.com.",
    aiRoutingNetwork: "AI-spørringer rutes via network.corifeus.com. Hvis du har din egen gratis Groq API-nøkkel, kan du slå av denne bryteren for å rute direkte til Groq uten network.corifeus.com.",
    aiMaxTokens: "AI-maksimalt antall tokens",
    aiMaxTokensInfo: "Maksimalt antall tokens for AI-svar. Høyere verdier gir lengre svar, men kan bruke flere API-kreditter.",
    ssh: {
      on: "SSH på",
      off: "SSH av",
      sshHost: "SSH Vert",
      sshPort: "SSH-port",
      sshUsername: "SSH brukernavn",
      sshPassword: "SSH passord",
      sshPrivateKey: "SSH privat nøkkel"
    },
    isBuffer: opts => `[object ArrayBuffer] betyr at verdien er binære data eller verdien er større enn ${opts.maxValueAsBuffer}`,
    streamValue: `Strømfelt og verdi er en oneliner. Eks.: felt1 verdi1 "felt 2" "verdi 2"`,
    streamTimestampId: `'*' betyr automatisk generert eller spesifikasjonen som <millisecondsTime>-<sequenceNumber>`,
    unableToLoadKey: ({
      key
    }) => {
      return `Kan ikke laste denne nøkkelen: ${key}. Mulig, nøkkelen ble slettet. Den nøyaktige feilen er i konsollen.`;
    },
    bigJson: "Dette JSON-objektet er over 10 kb, så sørg for at du vet hva du gjør, fordi noen funksjoner kan være treg gjengivelse.",
    addNode: "Legg til node",
    validateJson: "Valider JSON",
    reducedFunction: `Redusert funksjonalitet`,
    tooManyKeys: opts => {
      return `For de fulle maksimale funksjonene tillatte tastene totalt er ${opts.maxLightKeysCount} telle. Denne databasen har over de tillatte nøklene totalt ${opts.count}. Nøkkelsortering og ekstra fancy treinformasjon er deaktivert. Søket skjer bare på serveren i stedet for klientsøket.`;
    },
    redisCommandNotFound: "Ingen Redis-kommandotreff funnet ...",
    treeKeyStore: `Sorteringen (naturlig sammenligning) utføres på klienten aka nettleseren, noe som betyr at den har en straff for store store sett, som over 10k nøkler, det kan legge til litt tid til sidegjengivelsen. Det er ingen nøkkelsortering i Redis, bare slik.`,
    socketIoTimeout: options => {
      return `Socket.IO ble tidsavbrutt for denne forespørselen (maks ${options.timeout / 1000} sekunder) ...`;
    },
    resizerInfo: options => {
      return `Minste bredde på venstre eller høyre panel er ${options.width}px`;
    },
    jsonViewNotParsable: "Denne verdien er ikke JSON parserbar  ",
    ttlTitle: "Still inn TTL på sekunder",
    passwordSecure: "Passordet kan være tomt, men det vil fortsatt vise tegn, dette er en sikkerhetsfunksjon.",
    tlsWithoutCert: "Aktiver TLS uten ekstra sertifikat",
    tlsRejectUnauthorized: "Avvis uautorisert sertifikat",
    tlsSecure: "Hvis du ser en TLS-konfigurasjon som starter med en P3X eller alle TLS-innstillingene ser like ut, er det en sikker funksjon. For å endre innstillingene, erstatt disse innstillingene med tomme eller noe annet, og de vil bli lagret. Hvis du ikke endrer TLS-innstillingene, beholdes innstillingene slik de er på serveren.",
    treeSeparatorEmpty: "Hvis treskilleren er tom, vil treet ikke ha noen nestede noder, bare en ren liste",
    treeSeparatorEmptyNote: "Ingen nestede noder, bare en ren liste",
    welcomeConsole: "Velkommen til Redis-konsollen",
    welcomeConsoleInfo: "Markør OPP- eller NED-historikk er aktivert",
    redisListIndexInfo: "Tom for å legge til, -1 for å legge til eller lagre den til posisjonen som vises.",
    console: "Konsoll",
    connectiondAdd: "Legg til tilkobling",
    connectiondEdit: "Rediger tilkobling",
    connectiondView: "Se tilkoblingen",
    connections: "Tilkoblinger",
    keysSort: {
      on: "Nøkkelsortering på",
      off: "Nøkkelsortering"
    },
    cluster: {
      on: "Cluster på",
      off: "Cluster av"
    },
    sentinel: {
      on: "Sentinel på",
      off: "Sentinel av",
      name: "Sentinel navn"
    },
    readonly: {
      on: "Skrivebeskyttet på",
      off: "Skrivebeskyttet av"
    },
    theme: {
      light: "Lys",
      dark: "Mørk bedrift",
      darkNeu: "Mørkt",
      darkoBluo: "Mørk blå",
      enterprise: "Enterprise",
      redis: "Redis",
      matrix: "Matrise"
    },
    connected: opts => {
      return `Tilkoblet: ${opts.name}`;
    },
    tree: "Tre",
    askAuth: "Be om autorisasjon",
    keyboardShortcuts: "Keyboard Shortcuts",
    about: "About",
    supportedLanguages: "Supported Languages",
    version: "Version",
    redisVersion: "Redis Version",
    modules: "Moduler",
    shortcutRefresh: "Refresh",
    shortcutSearch: "Focus Search",
    shortcutNewKey: "New Key",
    shortcutDisconnect: "Koble fra",
    themeAuto: "Auto (system)",
    languageAuto: "Auto (system)",
    shortcutCommandPalette: "Command Palette",
    commandPalette: "Command Palette",
    noResults: "No results",
    redisCommandsReference: "Redis Kommandoer",
    ungrouped: "Uten gruppe",
    grouped: "Grouped",
    connectFirst: "Koble til en Redis-server først",
    searchLanguage: "Søk språk...",
    exportProgress: "Eksporterer nøkler...",
    importProgress: "Importerer nøkler...",
    importPreview: "Forhåndsvisning",
    importOverwrite: "Overskriv",
    importSkip: "Hopp over",
    importConflict: "Hvis nøkkelen allerede finnes:",
    noKeysToExport: "Ingen nøkler å eksportere",
    type: "Type",
    time: "Tid",
    format: "Format",
    loading: "Laster...",
    autoRefresh: "Auto",
    exportSearchHint: "Eksporterer kun nøkler som matcher gjeldende søk",
    importSearchHint: "Import gjelder for hele databasen, ikke bare søkeresultater",
    deleteSearchHint: "Sletter alle nøkler som matcher gjeldende søk på serveren",
    deletingSearchKeys: "Sletter matchende nøkler...",
    importNoKeys: "Ingen nøkler funnet i filen",
    desktopNotifications: "Skrivebordsvarsler",
    desktopNotificationsEnabled: "Aktiver skrivebordsvarsler",
    desktopNotificationsInfo: "Motta OS-varsler for Redis-frakoblinger og gjenoppkoblinger når appen ikke er i fokus."
  },
  status: {
    dataCopied: "Dataene er i utklippstavlen",
    exportDone: "Eksport fullført",
    deletedSearchKeys: (opts) => `${opts.count} nøkler slettet`,
    indexCreated: "Indeks opprettet",
    indexDropped: "Indeks slettet",
    importDone: (opts) => `Import fullført: ${opts.created} opprettet, ${opts.skipped} hoppet over, ${opts.errors} feil`,
    nodeRemoved: "Node fjernet",
    keyIsNotExisting: "Denne nøkkelen kan ha blitt slettet eller utløpt.",
    keyCount: opts => {
      if (opts.keyCount === 0) {
        return "Ingen nøkkel";
      } else if (opts.keyCount === 1) {
        return "1 nøkkel";
      } else {
        return `${opts.keyCount} nøkler`;
      }
    },
    treeExpandAll: "Utvid alle trebladene. Denne operasjonen kan være dyr og kan ta tid ...",
    noRedisKeys: "Det er ingen nøkler i denne databasen.",
    redisConnected: "Redis tilkoblet vellykket",
    reverted: "Angret",
    reloadingDataInfo: "Laster Redis datainfo på nytt",
    added: "Lagt til",
    saved: "Oppdatert",
    cancelled: "Kansellert",
    deleted: "Slettet",
    savedRedis: "Redis-data er lagret",
    redisDisconnected: opts => {
      return `Den gjeldende tilkoblingen hadde en feil: ${opts.error.message}`;
    },
    dbChanged: opts => {
      return `db-indeksen satt til ${opts.db}. `;
    },
    treeDeleted: opts => {
      return `Trenøkkelen ble slettet (${opts.key}).`;
    },
    deletedKey: opts => {
      return `Nøkkelen ble slettet (${opts.key}).`;
    },
    renamedKey: "Denne nøkkelen har fått nytt navn",
    ttlChanged: "Denne nøkkelens TTL er endret",
    notInteger: "Denne inngangen er ikke et heltall",
    persisted: "Denne nøkkelen er vedvart for alltid",
    set: "Nøkkelen er satt/lagt til",
    connectionRestored: "Tilkobling gjenopprettet"
  },
  code: {
    "delete-connection": "Denne tilkoblingen ble slettet, så du er frakoblet denne Redis-forekomsten.",
    "save-connection": "Denne tilkoblingen ble endret, så du er koblet fra denne Redis-forekomsten. Du kan koble til på nytt.",
    "readonly-connections": "Tilkoblinger legg til/lagre/slett er skrivebeskyttet!",
    "readonly-connection-mode": "Denne tilkoblingen er skrivebeskyttet modus!",
    "list-out-of-bounds": "Denne listeindeksen er utenfor grensene",
    "invalid-json-value": "Verdien er ikke gyldig JSON.",
    "http_auth_required": "Autorisasjon kreves: vennligst autentiser med HTTP Basic Auth og last inn på nytt.",
    "auto-connection-failed": "Mulig, tilkoblingen ble fjernet og den automatiske tilkoblingen mislyktes på grunn av dette.",
    invalid_console_command: "Denne kommandoen fungerer ikke via GUI.",
    "AI_DISABLED": "AI er deaktivert. Aktiver det i AI-innstillinger.",
    "AI_PROMPT_REQUIRED": "AI-forespørsel er påkrevd.",
    "GROQ_API_KEY_READONLY": "Groq API-nøkkelen er skrivebeskyttet og kan ikke endres.",
    "blocked_api_access": "Groq API-planen din tillater ikke tilgang til denne modellen. Oppgrader Groq-planen din eller bruk network.corifeus.com proxy.",
    "rate_limit": "AI-hastighetsgrense nådd. Prøv igjen senere eller bruk din egen Groq API-nøkkel i innstillingene."
  },
  form: {
    error: {
      required: "Obligatorisk",
      port: "Porten er mellom 1-65535",
      invalid: "Skjemaet er ugyldig"
    },
    connection: {
      label: {
        name: "Navn",
        group: "Group",
        host: "Vertsnavn",
        port: "Port",
        password: "Passord",
        username: "Brukernavn"
      }
    },
    treeSettings: {
      maxValueDisplay: "Maks verdi for visningsstrenglengde",
      maxValueDisplayInfo: "Hvis satt til 0, vis hele verdiene. Hvis større enn 0, avkort til denne lengden. Hvis -1: for strenger, skjul verdien til du redigerer; for andre typer, vis fullt innhold.",
      maxKeys: "Maks nøkkeltall",
      maxKeysInfo: "For at GUI ikke skal krasje, begrenser vi maks nøkkeltall.",
      keyCount: (opts) => {
        return `Antall nøkler: ${opts?.keyCount ?? 0}`;
      },
      label: {
        animation: "Bruk animasjon",
        noAnimation: "Ingen animasjon",
        undoEnabled: "Angre aktivert",
        undoDisabled: "Angre deaktivert",
        diffEnabled: "Vis diff f\u00f8r lagring",
        diffDisabled: "Diff f\u00f8r lagring er deaktivert",
        jsonFormatTwoSpace: "Formater JSON med 2 mellomrom",
        jsonFormatFourSpace: "Formater JSON med 4 mellomrom",
        formName: "Redis-innstillinger",
        searchModeClient: "Klientsøkemodus",
        searchModeServer: "Serversøkemodus",
        searchModeStartsWith: "Søk med starter med modus",
        searchModeIncludes: "Søk inkluderer modus"
      },
      undoHint: "Angre er bare tilgjengelig for n\u00f8kkeltypene string og JSON",
      field: {
        treeSeparator: "Treskiller",
        treeSeparatorSelector: "Treskillevelger",
        page: "Antall tresøking",
        keyPageCount: "Antall nøkkelsøking",
        keysSort: "Sorter nøklene",
        searchMode: "Søkemodus",
        searchModeStartsWith: "Søket starter med / inkluderer"
      },
      error: {
        keyPageCount: "Antall nøkkelsider må være et heltall mellom 5 og 100",
        page: "Sideantallet må være et heltall mellom 10 - 5000",
        maxValueDisplay: "Den maksimale visningsverdien må være et heltall mellom -1 og 32768",
        maxKeys: "Den maksimale nøkkeltallverdien må være et heltall mellom 100 og 100 000"
      }
    },
    key: {
      label: {
        formName: {
          add: "Legg til ny Redis-nøkkel",
          edit: "Rediger Redis nøkkel",
          append: "Legg til eksisterende Redis-nøkkel"
        }
      },
      field: {
        streamTimestamp: "Tidsstempel",
        key: "Nøkkel",
        type: "Type",
        index: "Indeks",
        hashKey: "Hash-nøkkel",
        score: "Score",
        value: "Verdi",
        errorRate: "Feilrate",
        capacity: "Kapasitet",
        topk: "Top K",
        width: "Bredde",
        depth: "Dybde",
        decay: "Forfall",
        compression: "Komprimering",
        increment: "Økning",
        item: "Element",
        vectorValues: "Vektorverdier (kommaseparert)",
        element: "Elementnavn",
      },
      error: {
        streamTimestamp: "Tidsstemplet er påkrevd, enten Redis-format eller som *",
        key: "Nøkkelen er minst ett tegn",
        hashKey: "Hash-tabellnøkkelen er minst ett tegn",
        score: "Den sorterte settpoengsummen er påkrevd",
        value: "Verdien er påkrevd",
        errorRate: "Feilraten må være mellom 0 og 1 (f.eks. 0.01)",
        capacity: "Kapasiteten må være et positivt heltall",
        topk: "Top K må være et positivt heltall",
        width: "Bredden må være et positivt heltall",
        depth: "Dybden må være et positivt heltall",
        item: "Elementet er påkrevd"
      }
    },
    main: {
      label: {
        database: "DB"
      }
    }
  },
  page: {
    search: {
      title: "Søk",
      index: "Indeks",
      query: "Spørring",
      results: "Resultater",
      noIndex: "Ingen indekser funnet",
      createIndex: "Opprett indeks",
      dropIndex: "Slett indeks",
      indexInfo: "Indeksinfo",
      indexName: "Indeksnavn",
      prefix: "Nøkkelprefiks (valgfritt)",
      fieldName: "Feltnavn",
      hybridMode: "Hybridsøk (FT.HYBRID)",
      vectorField: "Vektorfelt",
      vectorValues: "Vektorverdier",
    },
    monitor: {
      title: "Overvåking",
      memory: "Minne",
      opsPerSec: "Ops/sek",
      clients: "Klienter",
      blocked: "Blokkert",
      hitsMisses: "Treffrate",
      networkIo: "Nettverk I/O",
      slowLog: "Treg logg",
      totalCommands: "Totalt",
      expired: "Utløpt",
      evicted: "Kastet ut",
      clientList: "Klientliste",
      topKeys: "Største nøkler etter minne",
      killClient: "Avslutt klient",
      clientKilled: "Klient avsluttet",
      confirmKillClient: "Er du sikker på at du vil avslutte denne klienten?",
      noKeys: "Ingen nøkler",
      rss: "RSS",
      peak: "Topp",
      fragmentation: "Fragmentering",
      hitsAndMisses: "Treff / Bom",
      noClients: "Ingen klienter",
      slotStats: "Klynge slot statistikk",
      noSlowQueries: "Ingen trege søk registrert.",
      confirmSlowLogReset: "Er du sikker på at du vil tilbakestille den trege loggen?",
      slowLogResetDone: "Den trege loggen ble tilbakestilt.",
      clusterSlotMap: "Redis cluster slot map",
      slotRange: "Cluster spor rekkevidde",
      totalSlots: "Totale klyngeplasser",
      noClusterData: "Ingen Redis-klyngedata tilgjengelig.",
    },
    analysis: {
      title: "Minneanalyse",
      runAnalysis: "Kjør analyse",
      running: "Analyserer...",
      typeDistribution: "Typefordeling",
      prefixMemory: "Minne etter prefiks",
      topKeysByMemory: "Største nøkler etter minne",
      expirationOverview: "Nøkkelutløp",
      memoryBreakdown: "Minnefordeling",
      keysScanned: "Skannede nøkler",
      totalMemory: "Totalt minne",
      rssMemory: "RSS-minne",
      peakMemory: "Toppminne",
      luaMemory: "Lua-minne",
      overheadMemory: "Overhead",
      datasetMemory: "Datasett",
      fragmentation: "Fragmentering",
      allocator: "Allokator",
      withTTL: "Med TTL",
      persistent: "Permanente",
      avgTTL: "Gjennomsnittlig TTL",
      prefix: "Prefiks",
      keyCount: "Antall nøkler",
      memoryUsage: "Minnebruk",
      noPrefix: "(uten prefiks)",
      topN: "Top N",
      maxScanKeys: "Maks. skannede nøkler",
      type: "Type",
      noData: "Ingen data. Klikk Kjør analyse for å starte.",
      exportAll: "Eksporter alt",
      memoryDoctor: "Memory Doctor",
      doctorNoData: "Klikk Oppdater for å kjøre Memory Doctor-diagnostikk.",
    },
    acl: {
      title: "ACL-brukere",
      loadUsers: "Last inn brukere",
      username: "Brukernavn",
      status: "Status",
      enabled: "Aktivert",
      disabled: "Deaktivert",
      commands: "Kommandoer",
      keys: "Redis nøkkelmønstre",
      currentUser: "Gjeldende",
      createUser: "Opprett bruker",
      editUser: "Rediger bruker",
      deleteUser: "Slett",
      confirmDelete: "Er du sikker på at du vil slette ACL-brukeren?",
      userDeleted: "ACL-brukeren ble slettet.",
      userSaved: "ACL-brukeren ble lagret.",
      cannotDeleteDefault: "Kan ikke slette standardbrukeren.",
      cannotDeleteSelf: "Kan ikke slette den tilkoblede brukeren.",
      noUsers: "Klikk Last inn brukere for å se ACL-brukere. Krever Redis 6.0+.",
      rules: "Regler",
      rulesHint: "Mellomromseparerte tokens (for eksempel on >password +@all ~* &*)",
      defaultUserWarning: "Forsiktig: Endring av standardbrukeren kan låse alle tilkoblinger. Hvis dette skjer, må du starte Redis på nytt eller bruke redis-cli for å gjenopprette tilgangen.",
    },
    overview: {
      noConnected: "Det er ingen tilkobling til Redis.",
      overviewClients: "List de tilknyttede etter antall klienter",
      connectedCount: opt => {
        if (opt.length === 1) {
          return "1 klient";
        }
        return `${opt.length} klienter`;
      }
    },
    key: {
      label: {
        key: "Nøkkel",
        encoding: "Koding",
        compression: "Komprimering",
        aiRateLimited: "AI-forespørselsgrensen er nådd. Prøv igjen senere eller bruk din egen Groq API-nøkkel i Innstillinger.",
        aiError: "AI-spørring mislyktes",
        length: "Størrelse",
        ttl: "TTL",
        ttlTitle: "Tid å leve",
        type: "Type",
        ttlNotExpire: "utløper ikke",
        lengthString: "bytes",
        lengthItem: "gjenstander",
        actions: "Handlinger"
      },
      list: {
        table: {
          index: "Indeks",
          value: "Verdi"
        }
      },
      hash: {
        table: {
          hashkey: "Hashkey",
          value: "Verdi"
        }
      },
      set: {
        table: {
          value: "Medlem"
        }
      },
      zset: {
        table: {
          value: "Medlem",
          score: "Score"
        }
      },
      stream: {
        table: {
          timestamp: "Tidsstempel-ID",
          field: "Felt",
          value: "Verdi"
        }
      },
      timeseries: {
        chart: "Diagram",
        info: "Info",
        addPoint: "Legg til datapunkt",
        from: "Fra (ms eller -)",
        to: "Til (ms eller +)",
        aggregation: "Aggregering",
        timeBucket: "Tidsintervall (ms)",
        none: "Ingen",
        dataPoints: "datapunkter",
        labels: "Etiketter",
        rules: "Regler",
        retention: "Oppbevaring",
        timestamp: "Tidsstempel",
        value: "Verdi",
        retentionHint: "0 = ingen utlop, eller millisekunder",
        duplicatePolicy: "Duplikatpolicy",
        labelsHint: "nokkel1 verdi1 nokkel2 verdi2",
        timestampHint: "'*' betyr automatisk generering, eller tidsstempel i millisekunder",
        editAllHint: "Ett datapunkt per linje: tidsstempel verdi (tidsstempel kan vaere * for auto)",
        autoSpread: "Automatisk * spredningsintervall",
        formula: "Formel",
        formulaLinear: "Lineaer",
        formulaRandom: "Tilfeldig",
        formulaSawtooth: "Sagtann",
        formulaPoints: "Punkter",
        formulaAmplitude: "Amplitude",
        formulaOffset: "Forskyvning",
        generate: "Generer",
        exportChart: "Eksporter PNG",
        overlay: "Overlegg nokler",
        overlayHint: "Kommaseparerte nokler",
        mrangeFilter: "Etikettfilter",
        bulkMode: "Massegenerering",
        mrangeHint: "f.eks. sensor=temp"
      },
      probabilistic: {
        info: "Info",
        addItem: "Legg til element",
        checkItem: "Sjekk element",
        item: "Element",
        exists: "Eksisterer",
        doesNotExist: "Eksisterer ikke",
        topkList: "Topp elementer",
        topkCount: "Antall",
        queryCount: "Antall spørringer",
        queryResult: "Spørringsresultat",
        addedSuccessfully: "Element lagt til",
        deletedSuccessfully: "Element slettet",
        quantile: "Kvantil",
        quantileResult: "Resultat",
        noItems: "Ingen elementer å vise",
        resetConfirm: "Tilbakestille alle data i denne T-Digest?"
      },
      vectorset: {
        info: "Info",
        elements: "Elementer",
        similarity: "Likhetssøk",
        searchByElement: "Søk etter element",
        searchByVector: "Søk etter vektor",
        vectorValues: "Vektorverdier",
        element: "Element",
        score: "Poeng",
        count: "Antall",
        addElement: "Legg til element",
        attributes: "Attributter",
        noAttributes: "Ingen attributter",
        dimensions: "Dimensjoner",
        removeConfirm: "Fjerne dette elementet fra VectorSet?",
        noElements: "Ingen elementer",
        filter: "Filter",
        searchComplete: "Søk fullført",
      }
    },
    treeControls: {
      settings: "Treinnstillinger",
      expandAll: "Utvid alle",
      collapseAll: "Skjul alle",
      level: "Nivå",
      search: {
        search: "Søk i tastene",
        clear: "Slett gjeldende søk for å sette tomt",
        placeholderClient: "Søk på klientsiden",
        placeholderServer: "Søk på serversiden",
        info: (opts) => "Søket på klientsiden betyr at det samsvarer med teksten i søkeinndataene. Søket på serversiden betyr at det er som å søke i nøkkelmønstrene som *{søk-tekst}*. For store søkesett er det bedre å bruke søk på serversiden. For mindre søkesett er det bedre å bruke søkemodus på klientsiden." + ` Hvis nøklene er over ${opts?.maxLightKeysCount ?? 110000}, kan du bare søke på serversiden.`,
        largeSetInfo: "I et stort sett er søk på klientsiden deaktivert. så akkurat nå er det bare søk på serversiden som er mulig.",
        infoDetails: "For å finne ut hvordan søket fungerer, sjekk innstillingene"
      },
      pager: {
        next: "Neste",
        prev: "Forrige",
        first: "Først",
        last: "Sist"
      }
    }
  },
  time: {
    years: "år",
    months: "måneder",
    days: "dager",
    year: "år",
    month: "måned",
    day: "dag",
    second: "sekund",
    seconds: "sekunder",
    minute: "minutt",
    minutes: "minutter",
    hour: "time",
    hours: "timer"
  },
  redisTypes: {
    string: "String",
    list: "List",
    hash: "Hash table",
    set: "Set",
    zset: "Sorted set - zset",
    stream: "Stream",
    json: "JSON",
    timeseries: "Time Series",
    bloom: "Bloom filter",
    cuckoo: "Cuckoo filter",
    topk: "Top-K",
    cms: "Count-Min Sketch",
    tdigest: "T-Digest",
    vectorset: "VectorSet",
  }
};
module.exports = strings;
