const strings = {
  error: {
    server_error: "Սերվերի սխալ, խնդրում ենք կրկին փորձել",
    aiPromptTooLong: "AI հարցումը չափազանց երկար է (առավելագույնը 4096 նիշ)",
  },
  title: {
    donate: "Նվիրաբերել",
    donateTitle: "Աջակցեք P3X Redis UI-ին",
    donateDescription: "P3X Redis UI-ն անվճար, բաց կոդով նախագիծ է։ Հավելվածի, AI հնարավորությունների, Docker պատկերների, սերվերների և ենթակառուցվածքի պահպանումը ֆինանսավորվում է մշակողի սեփական միջոցներով։ Եթե այս գործիքը օգտակար եք համարում, խնդրում ենք մտածել դրա շարունակական զարգացմանը նվիրատվությամբ աջակցելու մասին։ Յուրաքանչյուր ներդրում օգնում է նախագծին մնալ կենդանի և շարունակել զարգանալ։ Շնորհակալություն։",
    jsonRecursive: "Բացվում են բոլոր տերևները",
    name: "P3X Redis UI",
    nameDonated: "P3X Redis UI+",
    main: "Ձախ ներքևի ընտրացանկից կարող եք ընտրել Redis կապ միանալու համար:",
    statistics: "Վիճակագրություն",
    error: "Սխալ",
    connectingRedis: "Միացում Redis-ին ...",
    socketioConnectError: "Socket.IO սխալ",
    db: "DB",
    server: "Սերվեր",
    clients: "Հաճախորդներ",
    memory: "Հիշողություն",
    persistence: "Պահպանում",
    stats: "Վիճակագրություն",
    replication: "Կրկնօրինակում",
    cpu: "CPU",
    cluster: "Կլաստեր",
    modules: "Մոդուլներ",
    errorstats: "Սխալների վիճակագրություն",
    commandstats: "Հրամանների վիճակագրություն",
    latencystats: "Ուշացման վիճակագրություն",
    keysizes: "Բանալիների չափեր",
    threads: "Թելեր",
  },
  confirm: {
    dropIndex: "Վստա՞հ եք, որ ցանկանում եք ջնջել այս ինդեքսը:",
    uploadBuffer: "Վստա՞հ եք, որ ցանկանում եք վերբեռնել այս երկուական տվյալները:",
    uploadBufferDone: "Երկուական տվյալները վերբեռնվել են",
    uploadBufferDoneAndSave: "Երկուական տվյալները վերբեռնվել և պահպանվել են սերվերում",
    title: "Հաստատել",
    alert: "Զգուշացում",
    info: "Տեղեկություն",
    deleteListItem: "Վստա՞հ եք, որ ցանկանում եք ջնջել այս ցանկի տարրը:",
    deleteHashKey: "Վստա՞հ եք, որ ցանկանում եք ջնջել այս հեշ բանալու տարրը:",
    deleteStreamTimestamp: "Վստա՞հ եք, որ ցանկանում եք ջնջել այս հոսքի ժամադրոշմը:",
    deleteSetMember: "Վստա՞հ եք, որ ցանկանում եք ջնջել այս բազմության անդամին:",
    deleteZSetMember: "Վստա՞հ եք, որ ցանկանում եք ջնջել այս տեսակավորված բազմության անդամին:",
    deleteConnection: "Հաստատել",
    deleteConnectionText: "Վստա՞հ եք, որ ցանկանում եք ջնջել այս Redis կապը:",
    deleteNode: "Վստա՞հ եք, որ ցանկանում եք ջնջել այս Redis հանգույցը:",
    deleteAllKeys: opts => {
      return `Ջնջե՞լ այս ծառը և դրա բոլոր բանալիները (${opts.key})?`;
    },
    deleteSearchKeys: opts => {
      return `Վստա՞հ եք, որ ցանկանում եք ջնջել "${opts.pattern}"-ին համապատասխանող բոլոր բանալիները: Գտնվել է ${opts.count} բանալի։`;
    },
    socketioConnectError: "Socket.IO-ը չի կարող միանալ սերվերին։ Կարող եք վերաբեռնել էջը և ինքներդ փորձել լուծել կապի խնդիրը, որովհետև հաճախորդը չի կարող դա ինքնուրույն շտկել։",
    socketioAuthRequired: "Պահանջվում է Socket.IO նույնականացում։ Խնդրում ենք նույնականանալ HTTP Basic Auth-ով (օգտանուն/գաղտնաբառ) և վերաբեռնել էջը։",
    invalidCredentials: "Անվավեր օգտանուն կամ գաղտնաբառ։",
    delete: "Ջնջե՞լ",
    deleteKey: "Վստա՞հ եք, որ ցանկանում եք ջնջել այս բանալին:",
    rename: {
      title: "Վստա՞հ եք, որ ցանկանում եք վերանվանել այս բանալին:",
      textContent: "Այս գործողությամբ բանալին մշտապես կվերանվանվի։",
      placeholder: "Redis բանալի (պարտադիր)"
    },
    ttl: {
      title: "Վստա՞հ եք, որ ցանկանում եք փոխել այս բանալու TTL-ը:",
      textContent: "TTL-ը փոխելը թարմացնում է այս բանալու կյանքի տևողությունը։ Դատարկ թողեք, եթե ցանկանում եք, որ այս բանալին պահպանվի ընդմիշտ։",
      placeholder: "Redis բանալու TTL (ամբողջ թիվ կամ դատարկ)",
      placeholderPlaceholder: "Դատարկը նշանակում է, որ այն կպահպանվի ընդմիշտ, հակառակ դեպքում մուտքագրեք ամբողջ թիվ։",
      convertTextToTime: "Փոխարկել տեքստը ժամանակի",
      convertTextToTimePlaceholder: "Օր. 1d կլինի 86400"
    },
  },
  language: {
    // When you translate the english name, keep the Language in English
    // eg. Inglés / English
    bg: "Български / Bulgarian",
    cs: "Čeština / Czech",
    de: "Deutsch / German",
    el: "Ελληνικά / Greek",
    en: "English",
    es: "Español / Spanish",
    fr: "Français / French",
    hu: "Magyar / Hungarian",
    it: "Italiano / Italian",
    ja: "日本語 / Japanese",
    nl: "Nederlands / Dutch",
    pl: "Polski / Polish",
    "pt-PT": "Português / Portuguese",
    ro: "Română / Romanian",
    ru: "Русский / Russian",
    sk: "Slovenčina / Slovak",
    sr: "Српски / Serbian",
    sv: "Svenska / Swedish",
    tr: "Türkçe / Turkish",
    uk: "Українська / Ukrainian",
    zn: "中文 / Chinese",
    ar: "العربية / Arabic",
    az: "Azərbaycanca / Azerbaijani",
    be: "Беларуская / Belarusian",
    bn: "বাংলা / Bengali",
    da: "Dansk / Danish",
    et: "Eesti / Estonian",
    fi: "Suomi / Finnish",
    fil: "Filipino / Filipino",
    he: "עברית / Hebrew",
    hr: "Hrvatski / Croatian",
    hy: "Հայերեն / Armenian",
    id: "Bahasa Indonesia / Indonesian",
    ka: "ქართული / Georgian",
    kk: "Қазақша / Kazakh",
    km: "ខ្មែរ / Khmer",
    ko: "한국어 / Korean",
    ky: "Кыргызча / Kyrgyz",
    lt: "Lietuvių / Lithuanian",
    mk: "Македонски / Macedonian",
    ms: "Bahasa Melayu / Malay",
    ne: "नेपाली / Nepali",
    no: "Norsk / Norwegian",
    "pt-BR": "Português (Brasil) / Portuguese (Brazil)",
    sl: "Slovenščina / Slovenian",
    tg: "Тоҷикӣ / Tajik",
    th: "ไทย / Thai",
    vi: "Tiếng Việt / Vietnamese",
    "zh-HK": "中文（香港） / Chinese (Hong Kong)",
    "zh-TW": "中文（台灣） / Chinese (Taiwan)",
    bs: "Bosanski / Bosnian",
    si: "සිංහල / Sinhala",
    sw: "Kiswahili / Swahili",
    ta: "தமிழ் / Tamil"
  },
  intention: {
    copy: "Պատճենել",
    downloadBuffer: "Ներբեռնել երկուական տվյալը",
    setBuffer: "Վերբեռնել երկուական տվյալը",
    exportKeys: "Արտահանել բանալիները",
    exportAllKeys: (opts) => `Արտահանել բոլոր ${opts.count} բանալիները`,
    exportSearchResults: (opts) => `Արտահանել ${opts.count} արդյունքները`,
    importKeys: "Ներմուծել բանալիները",
    deleteSearchKeys: (opts) => `Ջնջել ${opts.count} համապատասխանող բանալիները`,
    deleteAllKeysMenu: (opts) => `Ջնջել բոլոր ${opts.count} բանալիները`,
    saveWithFormatJson: "Պահպանել ձևաչափմամբ",
    formatJson: "Ձևաչափել JSON",
    wrap: "Տողադարձ",
    unwrap: "Առանց տողադարձի",
    downloadJson: "Ներբեռնել JSON",
    pubsubMonitor: "PubSub",
    pulse: "Զարկ",
    profiler: "Պրոֆայլեր",
    memoryAnalysis: "Վերլուծություն",
    // When you translate the language, keep the Language in English
    // eg. Idioma / Language
    language: "Լեզու / Language",
    ok: "Լավ",
    addKey: "Ավելացնել այս բանալիին",
    addKeyRoot: "Ավելացնել արմատային բանալի",
    reloadKey: "Վերաբեռնել բանալին",
    reload: "Վերաբեռնել",
    close: "Փակել",
    commands: "Հրամաններ",
    view: "Դիտել",
    statistics: "Վիճակագրություն",
    refresh: "Թարմացնել",
    pause: "Դադար",
    resume: "Շարունակել",
    clear: "Մաքրել",
    rename: "Վերանվանել",
    main: "Տվյալների բազա",
    cancel: "Չեղարկել",
    theme: "Թեմա",
    github: "GitHub",
    githubRepo: "Պահոց",
    githubRelease: "Թողարկումներ",
    githubChangelog: "Փոփոխությունների մատյան",
    info: "Տեղեկություն",
    settings: "Կարգավորումներ",
    connect: "Միացնել",
    disconnect: "Անջատել",
    logout: "Դուրս գալ",
    overview: "Ընդհանուր ակնարկ",
    console: "Վահանակ",
    noConnections: "Կապեր չկան, ավելացրեք կապ կարգավորումների ընտրացանկում։",
    noConnectionsInSettings: "Կապեր չկան, կարող եք վերևում ավելացնել ՆՈՐ ԿԱՊ։",
    connectionAdd: "Նոր կապ",
    addGroup: "Ավելացնել խումբ",
    extend: "Ընդլայնել",
    collapse: "Ծալել",
    add: "Ավելացնել",
    edit: "Խմբագրել",
    save: "Պահպանել",
    ttl: "Սահմանել TTL",
    fieldTtl: "Դաշտի TTL",
    digest: "Digest",
    delete: "Ջնջել",
    remove: "Հեռացնել",
    sure: "Հաստատել",
    areYouSure: "Վստա՞հ եք",
    testConnection: "Փորձարկել կապը",
    getKey: "Բեռնվում է Redis բանալին և դրա հետ կապված տվյալները ...",
    jsonViewShow: "Ցուցադրել JSON",
    jsonViewEditor: "Խմբագրել JSON",
    quickConsole: "Արագ վահանակ",
    moveUp: "Տեղափոխել վերև",
    moveDown: "Տեղափոխել ներքև",
  },
  label: {
    id: {
      nodeId: "Հանգույցի ID",
      id: "Կապի ID",
      info: "Եթե չեք ցանկանում փոխել sshPassword, sshPrivateKey, password, tlsCrt, tlsKey, tlsCa հատկությունները, խնդրում ենք այդ դաշտերում մուտքագրել կապի ID-ն, որպեսզի դրանց արժեքները պահպանվեն անփոփոխ։ Եթե նույն տրամաբանությունը ցանկանում եք կիրառել հանգույցի գաղտնաբառի համար, ապա հանգույցի գաղտնաբառի դաշտում մուտքագրեք հանգույցի ID-ն։"
    },
    secureFeature: "Եթե տեսնում եք արժեք, որը սկսվում է P3X-ով և նման է արդեն եղածին, դա անվտանգության հատկություն է։ Կարգավորումները փոխելու համար պարզապես փոխարինեք դրանք դատարկ կամ այլ արժեքով, և դրանք կպահպանվեն։ Եթե կարգավորումները չփոխեք, սերվերում պահված արժեքները կմնան անփոփոխ։",
    aiTranslating: "Թարգմանվում է...",
    aiSettings: "AI կարգավորումներ",
    desktopNotifications: "Աշխատասեղանի ծանուցումներ",
    desktopNotificationsEnabled: "Միացնել աշխատասեղանի ծանուցումները",
    desktopNotificationsInfo: "Ստացեք OS ծանուցումներ Redis անջատումների և վերամիացումների մասին, երբ հավելվածը ակտիվ պատուհանը չէ։",
    aiGroqApiKey: "Groq API բանալի",
    aiGroqApiKeyInfo: "Ընտրովի։ Ձեր սեփական Groq API բանալին ավելի լավ աշխատանքի համար։ Անվճար բանալի ստացեք այստեղից",
    aiGroqApiKeyPlaceholder: "gsk_...",
    aiGroqApiKeySaved: "AI կարգավորումները պահպանվել են",
    aiGroqApiKeyInvalid: "Groq API բանալին անվավեր է",
    aiGroqApiKeyNotSet: "Սահմանված չէ (օգտագործվում է սերվերի կանխադրվածը)",
    aiEnabled: "AI միացված է",
    aiEnabledYes: "Այո",
    aiEnabledNo: "Ոչ",
    aiRouteViaNetwork: "Ուղղորդել network.corifeus.com-ի միջոցով",
    aiRoutingDirect: "Հարցումները ուղիղ ուղարկվում են Groq՝ օգտագործելով ձեր API բանալին և շրջանցելով network.corifeus.com-ը։",
    aiRoutingNetwork: "AI հարցումները ուղղորդվում են network.corifeus.com-ի միջոցով։ Եթե ունեք ձեր սեփական անվճար Groq API բանալին, կարող եք անջատել այս փոխարկիչը, որպեսզի հարցումները ուղիղ գնան Groq՝ առանց network.corifeus.com-ի։",
    aiMaxTokens: "AI առավելագույն token-ներ",
    aiMaxTokensInfo: "AI պատասխանների token-ների առավելագույն քանակը։ Ավելի բարձր արժեքները թույլ են տալիս ավելի երկար պատասխաններ, բայց կարող են օգտագործել ավելի շատ API կրեդիտներ։",
    ssh: {
      on: "SSH միացված է",
      off: "SSH անջատված է",
      sshHost: "SSH host",
      sshPort: "SSH պորտ",
      sshUsername: "SSH օգտանուն",
      sshPassword: "SSH գաղտնաբառ",
      sshPrivateKey: "SSH private key"
    },
    isBuffer: opts => `[object ArrayBuffer] նշանակում է, որ արժեքը երկուական տվյալ է կամ արժեքի չափը մեծ է, քան ${opts.maxValueAsBuffer}`,
    streamValue: `Հոսքի դաշտն ու արժեքը պետք է լինեն մեկ տողում։ Օր. field1 value1 "field 2" "value 2"`,
    streamTimestampId: `'*' նշանակում է ավտոմատ գեներացված արժեք կամ <millisecondsTime>-<sequenceNumber> ձևաչափ`,
    unableToLoadKey: ({
      key
    }) => {
      return `Հնարավոր չէ բեռնել այս բանալին: ${key}։ Հնարավոր է՝ բանալին ջնջվել է։ Ճշգրիտ սխալը տեսեք վահանակում։`;
    },
    bigJson: "Այս JSON օբյեկտը 10 կԲ-ից մեծ է, այնպես որ համոզվեք, որ հասկանում եք՝ ինչ եք անում, քանի որ որոշ գործառույթներ կարող են դանդաղ աշխատել։",
    addNode: "Ավելացնել հանգույց",
    validateJson: "Ստուգել JSON-ը",
    reducedFunction: "Սահմանափակ ֆունկցիոնալություն",
    tooManyKeys: opts => {
      return `Լիարժեք ֆունկցիոնալության համար թույլատրված բանալիների առավելագույն ընդհանուր քանակը ${opts.maxLightKeysCount} է։ Այս տվյալների բազայում ընդհանուր առմամբ ${opts.count} բանալի կա, ինչը գերազանցում է սահմանաչափը։ Բանալիների տեսակավորումն ու ծառի լրացուցիչ տեղեկությունները անջատված են։ Որոնումը կատարվում է միայն սերվերում, ոչ թե հաճախորդի կողմից։`;
    },
    redisCommandNotFound: "Redis հրամանի համապատասխանություն չի գտնվել ...",
    treeKeyStore: "Տեսակավորումը (natural compare) կատարվում է հաճախորդի կողմից, այսինքն՝ բրաուզերում, ինչը մեծ հավաքածուների համար լրացուցիչ ծախս ունի։ Օրինակ՝ 10k-ից ավելի բանալիների դեպքում դա կարող է մի փոքր դանդաղեցնել էջի արտապատկերումը։ Redis-ում ներկառուցված բանալիների տեսակավորում չկա, միայն այս եղանակով։",
    socketIoTimeout: options => {
      return `Socket.IO-ի սպասման ժամանակը սպառվել է այս հարցման համար (առավելագույնը ${options.timeout / 1000} վայրկյան) ...`;
    },
    resizerInfo: options => {
      return `Ձախ կամ աջ վահանակի նվազագույն լայնությունը ${options.width}px է`;
    },
    jsonViewNotParsable: "Այս արժեքը չի վերլուծվում որպես JSON",
    ttlTitle: "Սահմանեք TTL-ը վայրկյաններով",
    passwordSecure: "Գաղտնաբառը կարող է դատարկ երևալ, բայց միևնույն է նիշեր կցուցադրվեն. սա անվտանգության հատկություն է։",
    tlsWithoutCert: "Միացնել TLS-ը առանց լրացուցիչ վկայագրի",
    tlsRejectUnauthorized: "Մերժել չարտոնված վկայագիրը",
    tlsSecure: "Եթե տեսնում եք TLS կարգավորում, որը սկսվում է P3X-ով, կամ բոլոր TLS կարգավորումները նույն տեսքն ունեն, դա անվտանգության հատկություն է։ Կարգավորումները փոխելու համար պարզապես փոխարինեք դրանք դատարկ կամ այլ արժեքով, և դրանք կպահպանվեն։ Եթե TLS կարգավորումները չփոխեք, սերվերում պահված արժեքները կմնան անփոփոխ։",
    treeSeparatorEmpty: "Եթե ծառի բաժանարարը դատարկ է, ծառը չի ունենա ներդրված հանգույցներ, այլ պարզապես մաքուր ցուցակ կլինի",
    treeSeparatorEmptyNote: "Ներդրված հանգույցներ չկան, պարզապես մաքուր ցուցակ",
    welcomeConsole: "Բարի գալուստ Redis վահանակ",
    welcomeConsoleInfo: "UP կամ DOWN սլաքների պատմությունը միացված է",
    redisListIndexInfo: "Դատարկ թողեք՝ վերջում ավելացնելու համար, -1՝ սկզբում տեղադրելու համար, կամ պահեք այն ցուցադրված դիրքում։",
    console: "Վահանակ",
    connectiondAdd: "Ավելացնել կապ",
    connectiondEdit: "Խմբագրել կապը",
    connectiondView: "Դիտել կապը",
    connections: "Կապեր",
    keysSort: {
      on: "Բանալիների տեսակավորումը միացված է",
      off: "Բանալիների տեսակավորումն անջատված է"
    },
    cluster: {
      on: "Կլաստերը միացված է",
      off: "Կլաստերն անջատված է"
    },
    sentinel: {
      on: "Sentinel միացված է",
      off: "Sentinel անջատված է",
      name: "Sentinel անուն"
    },
    readonly: {
      on: "Միայն կարդալու ռեժիմը միացված է",
      off: "Միայն կարդալու ռեժիմն անջատված է"
    },
    theme: {
      light: "Բաց",
      dark: "Մութ enterprise",
      darkNeu: "Մութ",
      darkoBluo: "Darko bluo",
      enterprise: "Enterprise",
      redis: "Redis",
      matrix: "Matrix"
    },
    connected: opts => {
      return `Միացված է: ${opts.name}`;
    },
    tree: "Ծառ",
    askAuth: "Հարցնել նույնականացում",
    keyboardShortcuts: "Ստեղնաշարի դյուրանցումներ",
    about: "Ծրագրի մասին",
    supportedLanguages: "Աջակցվող լեզուներ",
    version: "Տարբերակ",
    redisVersion: "Redis տարբերակ",
    modules: "Մոդուլներ",
    shortcutRefresh: "Թարմացնել",
    shortcutSearch: "Կենտրոնանալ որոնման վրա",
    shortcutNewKey: "Նոր բանալի",
    shortcutDisconnect: "Անջատել",
    themeAuto: "Ավտո (համակարգ)",
    languageAuto: "Auto (system)",
    shortcutCommandPalette: "Հրամանների պալիտրա",
    commandPalette: "Հրամանների պալիտրա",
    noResults: "Արդյունքներ չկան",
    redisCommandsReference: "Redis հրամաններ",
    connectFirst: "Սկզբում միացեք Redis սերվերին",
    ungrouped: "Չխմբավորված",
    grouped: "Խմբավորված",
    searchLanguage: "Որոնել լեզու...",
    exportProgress: "Արտահանվում են բանալիները...",
    importProgress: "Ներմուծվում են բանալիները...",
    importPreview: "Նախադիտում",
    importOverwrite: "Վերագրել",
    importSkip: "Բաց թողնել",
    importConflict: "Եթե բանալին արդեն գոյություն ունի:",
    noKeysToExport: "Արտահանելու բանալիներ չկան",
    type: "Տեսակ",
    time: "Ժամանակ",
    format: "Ձևաչափ",
    loading: "Բեռնվում է...",
    autoRefresh: "Ավտո",
    importNoKeys: "Ֆայլում բանալիներ չեն գտնվել",
    exportSearchHint: "Արտահանվում են միայն ընթացիկ որոնմանը համապատասխանող բանալիները",
    importSearchHint: "Ներմուծումը կիրառվում է ամբողջ տվյալների բազայի վրա, ոչ միայն որոնման արդյունքների",
    deleteSearchHint: "Սերվերում ջնջում է ընթացիկ որոնմանը համապատասխանող բոլոր բանալիները",
    deletingSearchKeys: "Ջնջվում են համապատասխանող բանալիները...",
  },
  status: {
    dataCopied: "Տվյալները պատճենվել են սեղմատախտակին",
    exportDone: "Արտահանումն ավարտվեց",
    deletedSearchKeys: (opts) => `Ջնջվել է ${opts.count} բանալի`,
    indexCreated: "Ինդեքսը ստեղծվեց",
    indexDropped: "Ինդեքսը ջնջվեց",
    importDone: (opts) => `Ներմուծումն ավարտվեց. ${opts.created} ստեղծվեց, ${opts.skipped} բաց թողնվեց, ${opts.errors} սխալ`,
    nodeRemoved: "Հանգույցը հեռացվեց",
    keyIsNotExisting: "Այս բանալին կարող էր ջնջված լինել կամ ժամկետանց լինել։",
    keyCount: opts => {
      if (opts.keyCount === 0) {
        return "Բանալի չկա";
      } else if (opts.keyCount === 1) {
        return "1 բանալի";
      } else {
        return `${opts.keyCount} բանալի`;
      }
    },
    treeExpandAll: "Բացվում են ծառի բոլոր տերևները։ Այս գործողությունը կարող է ծախսատար լինել և ժամանակ պահանջել ...",
    noRedisKeys: "Այս տվյալների բազայում բանալիներ չկան։",
    redisConnected: "Redis-ը հաջողությամբ միացավ",
    connectionRestored: "Կապը վերականգնվեց",
    reloadingDataInfo: "Redis տվյալները վերաբեռնվում են",
    added: "Ավելացվեց",
    saved: "Թարմացվեց",
    cancelled: "Չեղարկվեց",
    deleted: "Ջնջվեց",
    savedRedis: "Redis տվյալները պահպանվել են",
    redisDisconnected: opts => {
      return `Ընթացիկ կապում սխալ է առաջացել: ${opts.error.message}`;
    },
    dbChanged: opts => {
      return `DB ինդեքսը սահմանվեց ${opts.db}-ի վրա։`;
    },
    treeDeleted: opts => {
      return `Ծառի բանալին ջնջվեց (${opts.key})։`;
    },
    deletedKey: opts => {
      return `Բանալին ջնջվեց (${opts.key})։`;
    },
    renamedKey: "Այս բանալին վերանվանվեց",
    ttlChanged: "Այս բանալու TTL-ը փոխվեց",
    notInteger: "Այս մուտքագրումը ամբողջ թիվ չէ",
    persisted: "Այս բանալին պահպանվում է ընդմիշտ",
    set: "Բանալին սահմանվեց/ավելացվեց"
  },
  code: {
    "delete-connection": "Այս կապը ջնջվել է, ուստի դուք անջատվել եք այս Redis օրինակից։",
    "save-connection": "Այս կապը փոխվել է, ուստի դուք անջատվել եք այս Redis օրինակից։ Կարող եք կրկին միանալ։",
    "readonly-connections": "Կապերի ավելացումը/պահպանումը/ջնջումը միայն կարդալու ռեժիմում է։",
    "readonly-connection-mode": "Այս կապը միայն կարդալու ռեժիմում է։",
    "list-out-of-bounds": "Ցանկի այս ինդեքսը սահմաններից դուրս է",
    "invalid-json-value": "Արժեքը վավեր JSON չէ։",
    "http_auth_required": "Պահանջվում է նույնականացում. խնդրում ենք նույնականանալ HTTP Basic Auth-ով և վերաբեռնել էջը։",
    "auto-connection-failed": "Հնարավոր է, որ կապը հեռացվել է, և դրա պատճառով ավտոմատ կապը ձախողվել է։",
    invalid_console_command: "Այս հրամանը GUI-ի միջոցով չի աշխատում։",
    AI_DISABLED: "AI-ն անջատված է։ Միացրեք այն AI կարգավորումներում։",
    AI_PROMPT_REQUIRED: "AI հարցումը պարտադիր է։",
    GROQ_API_KEY_READONLY: "Groq API բանալին միայն ընթերցման համար է և չի կարող փոփոխվել։",
    blocked_api_access: "Ձեր Groq API փաթեթը թույլ չի տալիս մուտք գործել այս մոդելին։ Խնդրում ենք արդիականացնել Groq փաթեթը կամ օգտագործել network.corifeus.com proxy-ն։",
    rate_limit: "AI-ի արագության սահմանաչափը հասել է։ Փորձեք ավելի ուշ կամ օգտագործեք ձեր սեփական Groq API բանալին Կարգավորումներում։",
  },
  form: {
    error: {
      required: "Պարտադիր է",
      port: "Պորտը պետք է լինի 1-65535 միջակայքում",
      invalid: "Ձևը անվավեր է"
    },
    connection: {
      label: {
        name: "Անուն",
        group: "Խումբ",
        host: "Հոսթի անուն",
        port: "Պորտ",
        password: "Գաղտնաբառ",
        username: "Օգտանուն"
      }
    },
    treeSettings: {
      maxValueDisplay: "Առավելագույն ցուցադրվող արժեքի տողի երկարություն",
      maxValueDisplayInfo: "Եթե սահմանված է 0, ցուցադրել ամբողջական արժեքները։ Եթե մեծ է 0-ից, կտրել մինչև այս երկարությունը։ Եթե -1 է, ապա տողերի համար թաքցնել արժեքը մինչև խմբագրումը, իսկ այլ տեսակների համար ցուցադրել ամբողջ բովանդակությունը։",
      maxKeys: "Բանալիների առավելագույն քանակ",
      maxKeysInfo: "Որպեսզի GUI-ը չխափանվի, սահմանափակում ենք բանալիների առավելագույն քանակը։",
      keyCount: (opts) => {
        return `Բանալիների քանակը: ${opts?.keyCount ?? 0}`;
      },
      label: {
        animation: "Օգտագործել անիմացիա",
        noAnimation: "Առանց անիմացիայի",
        jsonFormatTwoSpace: "Ձևաչափել JSON-ը 2 բացատով",
        jsonFormatFourSpace: "Ձևաչափել JSON-ը 4 բացատով",
        formName: "Redis կարգավորումներ",
        searchModeClient: "Հաճախորդի որոնման ռեժիմ",
        searchModeServer: "Սերվերի որոնման ռեժիմ",
        searchModeStartsWith: "«Սկսվում է»-ով որոնման ռեժիմ",
        searchModeIncludes: "Պարունակում է որոնման ռեժիմ"
      },
      field: {
        treeSeparator: "Ծառի բաժանարար",
        treeSeparatorSelector: "Ծառի բաժանարարի ընտրիչ",
        page: "Ծառի էջավորման քանակ",
        keyPageCount: "Բանալու էջավորման քանակ",
        keysSort: "Տեսակավորել բանալիները",
        searchMode: "Որոնման ռեժիմ",
        searchModeStartsWith: "Սկսվում է / պարունակում է"
      },
      error: {
        keyPageCount: "Բանալու էջավորման քանակը պետք է լինի ամբողջ թիվ 5-ից 100 միջակայքում",
        page: "Էջավորման քանակը պետք է լինի ամբողջ թիվ 10-ից 5000 միջակայքում",
        maxValueDisplay: "Առավելագույն ցուցադրման արժեքը պետք է լինի ամբողջ թիվ -1-ից 32768 միջակայքում",
        maxKeys: "Բանալիների առավելագույն քանակի արժեքը պետք է լինի ամբողջ թիվ 100-ից 100000 միջակայքում"
      }
    },
    key: {
      label: {
        formName: {
          add: "Ավելացնել նոր Redis բանալի",
          edit: "Խմբագրել Redis բանալին",
          append: "Ավելացնել առկա Redis բանալիին"
        }
      },
      field: {
        streamTimestamp: "Ժամադրոշմ",
        key: "Բանալի",
        type: "Տեսակ",
        index: "Ինդեքս",
        hashKey: "Հեշ բանալի",
        score: "Միավոր",
        value: "Արժեք",
        errorRate: "Սխալի մակարդակ",
        capacity: "Տարողություն",
        topk: "Top-K",
        width: "Լայնություն",
        depth: "Խորություն",
        decay: "Քայքայում",
        compression: "Սեղմում",
        increment: "Ավելացում",
        item: "Տարր",
        vectorValues: "Վեկտորի արժեքներ (ստորակետերով բաժանված)",
        element: "Տարրի անուն",
      },
      error: {
        streamTimestamp: "Ժամադրոշմը պարտադիր է, կամ Redis ձևաչափով, կամ որպես *",
        key: "Բանալին պետք է ունենա առնվազն մեկ նիշ",
        hashKey: "Հեշ բանալին պետք է ունենա առնվազն մեկ նիշ",
        score: "Տեսակավորված բազմության միավորը պարտադիր է",
        value: "Արժեքը պարտադիր է",
        errorRate: "Սխալի մակարդակը պետք է լինի 0-ից 1-ի միջև (օր. 0.01)",
        capacity: "Տարողությունը պետք է լինի դրական ամբողջ թիվ",
        topk: "Top-K-ը պետք է լինի դրական ամբողջ թիվ",
        width: "Լայնությունը պետք է լինի դրական ամբողջ թիվ",
        depth: "Խորությունը պետք է լինի դրական ամբողջ թիվ",
        item: "Տարրը պարտադիր է",
      }
    },
    main: {
      label: {
        database: "DB"
      }
    }
  },
  page: {
    search: {
      title: "Որոնում",
      index: "Ինդեքս",
      query: "Հարցում",
      results: "Արդյունքներ",
      noIndex: "Ինդեքսներ չեն գտնվել",
      createIndex: "Ստեղծել ինդեքս",
      dropIndex: "Ջնջել ինդեքսը",
      indexInfo: "Ինդեքսի տեղեկություն",
      indexName: "Ինդեքսի անուն",
      prefix: "Բանալու նախածանց (ըստ ցանկության)",
      fieldName: "Դաշտի անուն",
      hybridMode: "Հիբրիդ որոնում (FT.HYBRID)",
      vectorField: "Վեկտորային դաշտ",
      vectorValues: "Վեկտորի արժեքներ",
    },
    monitor: {
      title: "Մոնիտորինգ",
      memory: "Հիշողություն",
      opsPerSec: "Գործ./վ",
      clients: "Հաճախորդներ",
      blocked: "Արգելափակված",
      hitsMisses: "Հիթերի տոկոս",
      networkIo: "Ցանց I/O",
      slowLog: "Դանդաղ մատյան",
      totalCommands: "Ընդհանուր",
      expired: "Ժամկետանց",
      evicted: "Հեռացված",
      clientList: "Հաճախորդների ցանկ",
      topKeys: "Հիշողությամբ ամենամեծ բանալիները",
      killClient: "Անջատել հաճախորդին",
      clientKilled: "Հաճախորդն անջատվեց",
      confirmKillClient: "Վստա՞հ եք, որ ցանկանում եք անջատել այս հաճախորդին:",
      noKeys: "Բանալիներ չկան",
      rss: "RSS",
      peak: "Պիկ",
      fragmentation: "Ֆրագմենտացիա",
      hitsAndMisses: "Հիթեր / Վրիպումներ",
      noClients: "Հաճախորդներ չկան",
      slotStats: "Cluster slot-երի վիճակագրություն",
    },
    analysis: {
      title: "Հիշողության վերլուծություն",
      runAnalysis: "Գործարկել վերլուծությունը",
      running: "Վերլուծվում է...",
      typeDistribution: "Տեսակների բաշխում",
      prefixMemory: "Հիշողությունն ըստ նախածանցի",
      topKeysByMemory: "Հիշողությամբ ամենամեծ բանալիները",
      expirationOverview: "Բանալիների ժամկետայնություն",
      memoryBreakdown: "Հիշողության բաղադրիչներ",
      keysScanned: "Սկանավորված բանալիներ",
      totalMemory: "Ընդհանուր հիշողություն",
      rssMemory: "RSS հիշողություն",
      peakMemory: "Պիկ հիշողություն",
      luaMemory: "Lua հիշողություն",
      overheadMemory: "Վերադիր ծախս",
      datasetMemory: "Տվյալների հավաքածու",
      fragmentation: "Ֆրագմենտացիա",
      allocator: "Հատկացնող",
      withTTL: "TTL-ով",
      persistent: "Մշտական",
      avgTTL: "Միջին TTL",
      prefix: "Նախածանց",
      keyCount: "Բանալիների քանակ",
      memoryUsage: "Հիշողության օգտագործում",
      noPrefix: "(առանց նախածանցի)",
      topN: "Top N",
      maxScanKeys: "Սքանավորվող բանալիների առավելագույն քանակ",
      type: "Տեսակ",
      noData: "Տվյալներ չկան։ Սեղմեք «Գործարկել վերլուծությունը»՝ սկսելու համար։",
      exportAll: "Արտահանել բոլորը",
    },
    overview: {
      noConnected: "Redis-ի հետ կապ չկա։",
      overviewClients: "Ցուցադրել միացվածները ըստ հաճախորդների քանակի",
      connectedCount: opt => {
        if (opt.length === 1) {
          return "1 հաճախորդ";
        }
        return `${opt.length} հաճախորդներ`;
      }
    },
    key: {
      label: {
        key: "Բանալի",
        encoding: "Կոդավորում",
        compression: "Սեղմում",
        aiRateLimited: "AI-ի արագության սահմանաչափը հասել է։ Փորձեք ավելի ուշ կամ օգտագործեք ձեր սեփական Groq API բանալին Կարգավորումներում։",
        aiError: "AI հարցումը ձախողվեց",
        length: "Չափ",
        ttl: "TTL",
        ttlTitle: "Կյանքի տևողություն",
        type: "Տեսակ",
        ttlNotExpire: "չի ժամկետանցվում",
        lengthString: "բայթ",
        lengthItem: "տարր",
        actions: "Գործողություններ"
      },
      list: {
        table: {
          index: "Ինդեքս",
          value: "Արժեք"
        }
      },
      hash: {
        table: {
          hashkey: "Հեշ բանալի",
          value: "Արժեք"
        }
      },
      set: {
        table: {
          value: "Անդամ"
        }
      },
      zset: {
        table: {
          value: "Անդամ",
          score: "Միավոր"
        }
      },
      stream: {
        table: {
          timestamp: "Ժամադրոշմի ID",
          field: "Դաշտ",
          value: "Արժեք"
        }
      },
      timeseries: {
        chart: "Գրաֆիկ",
        info: "Տեղեկություն",
        addPoint: "Ավելացնել տվյալների կետ",
        from: "Սկսած (ms կամ -)",
        to: "Մինչև (ms կամ +)",
        aggregation: "Ագրեգացիա",
        timeBucket: "Bucket (ms)",
        none: "Ոչ մեկը",
        dataPoints: "տվյալների կետ",
        labels: "Պիտակներ",
        rules: "Կանոններ",
        retention: "Պահպանում",
        timestamp: "Ժամադրոշմ",
        value: "Արժեք",
        retentionHint: "0 = առանց ժամկետի ավարտի, կամ միլիվայրկյաններ",
        duplicatePolicy: "Կրկնօրինակների քաղաքականություն",
        labelsHint: "key1 value1 key2 value2",
        timestampHint: "'*' նշանակում է ավտոմատ գեներացված կամ միլիվայրկյաններով ժամադրոշմ",
        editAllHint: "Մեկ տվյալների կետ յուրաքանչյուր տողում՝ timestamp value (timestamp-ը կարող է լինել * ավտոմատ գեներացման համար)",
        autoSpread: "Ավտոմատ * տարածման միջակայք",
        formula: "Բանաձև",
        formulaLinear: "Գծային",
        formulaRandom: "Պատահական",
        formulaSawtooth: "Ատամնավոր",
        formulaPoints: "Կետեր",
        formulaAmplitude: "Ամպլիտուդ",
        formulaOffset: "Շեղում",
        generate: "Գեներացնել",
        overlay: "Վերադրել բանալիներ",
        overlayHint: "Ստորակետերով բաժանված բանալիներ",
        exportChart: "Արտահանել PNG",
        mrangeFilter: "Պիտակի զտիչ",
        mrangeHint: "օր. sensor=temp",
        bulkMode: "Զանգվածային գեներացում"
      },
      probabilistic: {
        info: "Տեղեկություն",
        addItem: "Ավելացնել տարր",
        checkItem: "Ստուգել տարրը",
        item: "Տարր",
        exists: "Գոյություն ունի",
        doesNotExist: "Գոյություն չունի",
        topkList: "Առաջատար տարրեր",
        topkCount: "Քանակ",
        queryCount: "Հարցումների քանակ",
        queryResult: "Հարցման արդյունք",
        addedSuccessfully: "Տարրը հաջողությամբ ավելացվեց",
        deletedSuccessfully: "Տարրը հաջողությամբ ջնջվեց",
        quantile: "Քվանտիլ",
        quantileResult: "Արդյունք",
        noItems: "Ցուցադրելու տարրեր չկան",
        resetConfirm: "Զրոյացնե՞լ այս T-Digest-ի բոլոր տվյալները:",
      },
      vectorset: {
        info: "Տեղեկություն",
        elements: "Տարրեր",
        similarity: "Նմանության որոնում",
        searchByElement: "Որոնել ըստ տարրի",
        searchByVector: "Որոնել ըստ վեկտորի",
        vectorValues: "Վեկտորի արժեքներ",
        element: "Տարր",
        score: "Միավոր",
        count: "Քանակ",
        addElement: "Ավելացնել տարր",
        attributes: "Հատկանիշներ",
        noAttributes: "Հատկանիշներ չկան",
        dimensions: "Չափեր",
        removeConfirm: "Հեռացնե՞լ այս տարրը VectorSet-ից:",
        noElements: "Տարրեր չկան",
        filter: "Զտիչ",
        searchComplete: "Որոնումն ավարտվեց",
      }
    },
    treeControls: {
      settings: "Ծառի կարգավորումներ",
      expandAll: "Բացել բոլորը",
      collapseAll: "Ծալել բոլորը",
      level: "Մակարդակ",
      search: {
        search: "Որոնել բանալիներում",
        clear: "Մաքրել ընթացիկ որոնումը, որպեսզի այն դատարկ լինի",
        placeholderClient: "Որոնել հաճախորդի կողմից",
        placeholderServer: "Որոնել սերվերի կողմից",
        info: (opts) => "Հաճախորդի կողմից որոնումը նշանակում է, որ համընկնումը կատարվում է որոնման դաշտում մուտքագրված տեքստի հետ։ Սերվերի կողմից որոնումը նշանակում է, որ բանալիներում որոնումը կատարվում է *{search-text}* տեսակի նախշով։ Մեծ որոնման հավաքածուների դեպքում ավելի լավ է օգտագործել սերվերի կողմից որոնումը։ Փոքր հավաքածուների դեպքում ավելի լավ է օգտագործել հաճախորդի կողմից որոնման ռեժիմը։" + ` Եթե բանալիների քանակը գերազանցում է ${opts?.maxLightKeysCount ?? 110000}-ը, կարող եք որոնել միայն սերվերի կողմից։`,
        largeSetInfo: "Մեծ հավաքածուներում հաճախորդի կողմից որոնումն անջատված է, ուստի այս պահին հնարավոր է միայն սերվերի կողմից որոնումը։",
        infoDetails: "Որոնման աշխատանքի մասին իմանալու համար տեսեք կարգավորումները"
      },
      pager: {
        next: "Հաջորդ",
        prev: "Նախորդ",
        first: "Առաջին",
        last: "Վերջին"
      }
    }
  },
  time: {
    years: "տարիներ",
    months: "ամիսներ",
    days: "օրեր",
    year: "տարի",
    month: "ամիս",
    day: "օր",
    second: "վայրկյան",
    seconds: "վայրկյաններ",
    minute: "րոպե",
    minutes: "րոպեներ",
    hour: "ժամ",
    hours: "ժամեր"
  },
  redisTypes: {
    string: "Տող",
    list: "Ցանկ",
    hash: "Հեշ աղյուսակ",
    set: "Բազմություն",
    zset: "Տեսակավորված բազմություն - zset",
    stream: "Հոսք",
    json: "JSON",
    timeseries: "Time Series",
    bloom: "Bloom filter",
    cuckoo: "Cuckoo filter",
    topk: "Top-K",
    cms: "Count-Min Sketch",
    tdigest: "T-Digest",
    vectorset: "VectorSet",
  }
};
module.exports = strings;
