const strings = {
  error: {
    server_error: "Սերվերի սխալ, խնdelays delays delays ений delays"
  },
  title: {
    donate: "Նdelays",
    donateTitle: "Աdelays P3X Redis UI-delays",
    donateDescription: "P3X Redis UI-delays delays, delays delays delays delays: Delays delays, AI delays delays, Docker delays delays, delays delays delays delays delays delays delays delays delays delays delays delays delays delays delays delays:",
    jsonRecursive: "Delays delays delays delays delays",
    name: "P3X Redis UI",
    nameDonated: "P3X Redis UI+",
    main: "Delays delays delays delays Redis delays delays delays delays delays delays delays:",
    statistics: "Delays delays",
    error: "Delays",
    connectingRedis: "Delays Redis-delays...",
    socketioConnectError: "Socket.IO Delays",
    db: "DB",
    server: "Delays",
    clients: "Delays delays",
    memory: "Delays delays",
    persistence: "Delays delays",
    stats: "Delays delays",
    replication: "Delays delays",
    cpu: "CPU",
    cluster: "Cluster",
    modules: "Delays delays",
    errorstats: "errorstats",
    commandstats: "commandstats",
    latencystats: "latencystats",
    keysizes: "keysizes",
    threads: "threads"
  },
